import { describe, it } from 'mocha';
import assert from 'assert';
import {
  ObjectFile, ObjectSection, ObjectSymbol,
  SymbolType, SymbolVisibility, SectionType
} from '../../src/linker/objectfile.js';
import { WlaDxCodegen, WlaDxSectionType } from '../../src/linker/wladxcodegen.js';

describe('WlaDxCodegen', () => {
  it('should generate WLA DX header', () => {
    const codegen = new WlaDxCodegen();
    const output = codegen.generate([]);
    assert.ok(output.includes('OPTION ROMSIZE'));
    assert.ok(output.includes('OPTION RAMSIZE'));
  });

  it('should generate section directives', () => {
    const objFile = new ObjectFile('test.o');
    const section = new ObjectSection('.text', SectionType.CODE);
    section.appendByte(0x00);
    objFile.addSection(section);

    const codegen = new WlaDxCodegen();
    const output = codegen.generate([objFile]);
    assert.ok(output.includes('SECTION'));
  });

  it('should generate DB directives for bytes', () => {
    const objFile = new ObjectFile('test.o');
    const section = new ObjectSection('.text', SectionType.CODE);
    section.appendByte(0x3E);
    section.appendByte(0x42);
    objFile.addSection(section);

    const codegen = new WlaDxCodegen();
    const output = codegen.generate([objFile]);
    assert.ok(output.includes('DB'));
  });

  it('should skip comment header when disabled', () => {
    const codegen = new WlaDxCodegen({ commentHeader: false });
    const output = codegen.generate([]);
    assert.ok(!output.includes('Generated by vcc80'));
  });

  it('should generate from config', () => {
    const codegen = new WlaDxCodegen();
    const output = codegen.generateFromConfig({
      sectionName: 'Code',
      sectionType: 'code',
      bytes: new Uint8Array([0x3E, 0x42, 0xC9]),
      labels: [{ name: 'START' }],
      data: []
    });

    assert.ok(output.includes('SECTION'));
    assert.ok(output.includes('START:'));
    assert.ok(output.includes('DB'));
  });

  it('should generate project with multiple files', () => {
    const objFile1 = new ObjectFile('a.o');
    const section1 = new ObjectSection('.text', SectionType.CODE);
    section1.appendByte(0xC9);
    objFile1.addSection(section1);
    objFile1.addSymbol(new ObjectSymbol('main', SymbolType.FUNCTION, SymbolVisibility.GLOBAL, 0, '.text'));

    const objFile2 = new ObjectFile('b.o');
    const section2 = new ObjectSection('.data', SectionType.DATA);
    section2.appendByte(0x00);
    objFile2.addSection(section2);
    objFile2.addSymbol(new ObjectSymbol('globalVar', SymbolType.VARIABLE, SymbolVisibility.GLOBAL, 0, '.data'));

    const codegen = new WlaDxCodegen();
    const output = codegen.generateProject({
      files: [objFile1, objFile2],
      entryPoint: 'main'
    });

    assert.ok(output.includes('main:'));
    assert.ok(output.includes('SECTION'));
  });

  it('should format values correctly', () => {
    const codegen = new WlaDxCodegen();
    assert.strictEqual(codegen.formatValue(255), '$FF');
    assert.strictEqual(codegen.formatValue(0), '$0');
    assert.strictEqual(codegen.formatValue('label'), 'label');
  });
});

describe('WlaDxSectionType', () => {
  it('should map code to ROM', () => {
    assert.strictEqual(WlaDxSectionType.code, 'ROM');
  });

  it('should map data to WRAM', () => {
    assert.strictEqual(WlaDxSectionType.data, 'WRAM');
  });

  it('should map bss to WRAM', () => {
    assert.strictEqual(WlaDxSectionType.bss, 'WRAM');
  });

  it('should map rodata to ROM', () => {
    assert.strictEqual(WlaDxSectionType.rodata, 'ROM');
  });
});
