/**
 * Z80 Code Generator - transforms IR to Z80 assembly
 */
import { 
  Instruction, BasicBlock, FunctionIR, ProgramIR,
  LoadInstruction, StoreInstruction, BinaryOpInstruction, UnaryOpInstruction,
  CallInstruction, ReturnInstruction, JumpIfInstruction, JumpInstruction,
  LabelInstruction, AllocStackInstruction, FreeStackInstruction, PushInstruction, PopInstruction,
  IntrinsicInstruction, LoadAddrInstruction, DerefLoadInstruction, DerefStoreInstruction,
  IndexedLoadInstruction, IndexedStoreInstruction, CallIndirectInstruction,
  CALLING_CONVENTION_CDECL, CALLING_CONVENTION_FASTCALL, CALLING_CONVENTION_CALLEE, CALLING_CONVENTION_NEW_Sdcc, CALLING_CONVENTION_DEFAULT
} from '../nanopass/il.js';

/**
 * Z80 Register names used in code generation
 */
export const Registers = {
  A: 'a',      // Accumulator (primary)
  B: 'b',      // General purpose register pair BC
  C: 'c',      // General purpose register pair BC
  D: 'd',      // General purpose register pair DE
  E: 'e',      // General purpose register pair DE
  H: 'h',      // General purpose register pair HL
  L: 'l',      // General purpose register pair HL
  IX: 'ix',    // Index register X
  IY: 'iy',    // Index register Y
  SP: 'sp',    // Stack pointer
  PC: 'pc'     // Program counter (implicit)
};

/**
 * Z80 Code Generator class
 */
export class Z80Codegen {
  /**
   * Creates a new Z80 code generator
   * @param {Object} options - Generation options
   */
  constructor(options = {}) {
    this.options = {
      outputDebugInfo: false,
      optimizeStack: true,
      ...options
    };

    this.currentFunction = null;
    this.labelsUsed = new Set();
    this.tempVariables = new Map();
    this.nextTempId = 0;
    
    // Generated assembly code buffer
    this.codeLines = [];
  }

  /**
    * Generates Z80 assembly from a program IR
    * @param {ProgramIR} ir - Program intermediate representation
    * @returns {string} Generated Z80 assembly source
    */
   generate(ir) {
     this.reset();
     
     // Build function lookup map for variadic detection
     this.currentFunctions = new Map();
     if (ir.functions && ir.functions.length > 0) {
       for (const func of ir.functions) {
         this.currentFunctions.set(func.name, func);
       }
     }
     
     // Generate header
     this.generateHeader();

     // Generate global data section
     if (ir.globals && ir.globals.length > 0) {
       this.codeLines.push('');
       this.codeLines.push('; Global Data Section');
       for (const global of ir.globals) {
         this.generateGlobal(global);
       }
     }

     // Generate functions
     if (ir.functions && ir.functions.length > 0) {
       for (const func of ir.functions) {
         this.currentFunction = func;
         this.codeLines.push('');
         this.generateFunction(func);
       }
     }

     return this.codeLines.join('\n') + '\n';
   }

  /**
    * Resets internal state for new code generation
    */
   reset() {
     this.currentFunction = null;
     this.currentFunctions = undefined;
     this.labelsUsed.clear();
     this.tempVariables.clear();
     this.nextTempId = 0;
     this.codeLines = [];
   }

  /**
   * Generates the assembler header/directives
   */
  generateHeader() {
    this.codeLines.push('; Generated by vcc80 - Z80 C Compiler');
    this.codeLines.push('');
    this.codeLines.push('; Entry point (optional)');
    this.codeLines.push('');
  }

  /**
   * Generates a global variable definition
   * @param {Object} global - Global variable descriptor
   */
  generateGlobal(global) {
    const name = global.name;
    
    if (global.type === 'string') {
      this.codeLines.push(`${name}: .db ${global.bytes.join(', ')}`);
    } else if (global.type === 'data') {
      // Data declaration: db, dw
      if (global.value !== undefined) {
        this.codeLines.push(`${name}: .db ${this.formatValue(global.value)}`);
      } else {
        // Reserved space
        const size = global.size || 1;
        this.codeLines.push(`${name}: .ds ${size}`);
      }
    } else if (global.type === 'bss') {
      // Uninitialized data
      this.codeLines.push(`${name}: .ds ${global.size || 1}`);
    } else {
      const size = global.size || 1;
      this.codeLines.push(`${name}: .ds ${size}`);
    }
  }

  /**
   * Generates a complete function definition
   * @param {FunctionIR} func - Function IR
   */
  generateFunction(func) {
    const name = func.name;
    
    this.codeLines.push('');
    this.codeLines.push('; Function: ' + name);
    this.codeLines.push(`${name}:`);

    // Generate prologue if needed (stack setup)
    this.generatePrologue(func);

    // Generate basic blocks in order
    for (const block of func.blocks) {
      this.generateBasicBlock(block);
    }

    // Generate epilogue
    this.generateEpilogue(func);
  }

  /**
   * Generates function prologue (stack frame setup)
   * @param {FunctionIR} func - Function IR
   */
  generatePrologue(func) {
    // Use IX as frame pointer for proper stack frame management
    // Save old IX, set IX = SP, then allocate local space
    this.codeLines.push(`  push ix`);
    this.codeLines.push(`  ld ix, sp`);

    // Calculate total stack space needed from AllocStackInstruction
    let totalSpace = 0;
    for (const block of func.blocks) {
      for (const instr of block.instructions) {
        if (instr instanceof AllocStackInstruction) {
          totalSpace += instr.operands[0];
        }
      }
    }

    if (totalSpace > 0) {
      if (totalSpace <= 255) {
        this.codeLines.push(`  ld b, ${totalSpace}`);
        this.codeLines.push('  dec_sp_loop:');
        this.codeLines.push('  dec sp');
        this.codeLines.push('  dec b');
        this.codeLines.push(`  ld a, b`);
        this.codeLines.push('  or a');
        this.codeLines.push('  jp nz, dec_sp_loop');
      } else {
        this.codeLines.push(`  ld hl, ${totalSpace}`);
        this.codeLines.push('  add hl, sp');
        this.codeLines.push('  ld sp, hl');
      }
    }
  }

  /**
   * Generates function epilogue (stack frame teardown)
   * @param {FunctionIR} func - Function IR
   */
  generateEpilogue(func) {
    // Restore frame pointer and return
    this.codeLines.push('  pop ix');
    this.codeLines.push('  ret');
  }

  /**
   * Generates a basic block of instructions
   * @param {BasicBlock} block - Basic block to generate
   */
  generateBasicBlock(block) {
    // Generate label for the block
    this.codeLines.push(`${block.name}:`);

    for (const instr of block.instructions) {
      this.generateInstruction(instr);
    }

    // Handle implicit fall-through to successor
    const isEntry = block === this.currentFunction.blocks[0];
    if (!isEntry && block.successor) {
      const lastInstr = block.instructions[block.instructions.length - 1];
      if (!(lastInstr instanceof JumpInstruction ||
            lastInstr instanceof JumpIfInstruction ||
            lastInstr instanceof ReturnInstruction)) {
        this.codeLines.push(`  jp ${block.successor.name}`);
      }
    }
  }

  /**
   * Generates a single IL instruction to Z80 assembly
   * @param {Instruction} instr - Instruction to generate
   */
  generateInstruction(instr) {
    switch (instr.opcode) {
      case 'LOAD':
        this.generateLoad(instr);
        break;

      case 'STORE':
        this.generateStore(instr);
        break;

      case 'BINOP':
        this.generateBinaryOp(instr);
        break;

      case 'UNOP':
        this.generateUnaryOp(instr);
        break;

      case 'CALL':
        this.generateCall(instr);
        break;

      case 'RET':
        this.generateReturn(instr);
        break;

      case 'JUMP_IF':
        this.generateJumpIf(instr);
        break;

      case 'JUMP':
        this.generateJump(instr);
        break;

      case 'LABEL':
        // Labels are generated at block level, skip here
        break;

      case 'ALLOC_STACK':
        this.generateAllocStack(instr);
        break;

      case 'FREE_STACK':
        this.generateFreeStack(instr);
        break;

      case 'PUSH':
        this.generatePush(instr);
        break;

      case 'POP':
        this.generatePop(instr);
        break;

      case 'INTRINSIC':
        this.generateIntrinsic(instr);
        break;

      case 'LOAD_ADDR':
        this.generateLoadAddr(instr);
        break;

      case 'DEREF_LOAD':
        this.generateDerefLoad(instr);
        break;

      case 'DEREF_STORE':
        this.generateDerefStore(instr);
        break;

      case 'INDEXED_LOAD':
        this.generateIndexedLoad(instr);
        break;

      case 'INDEXED_STORE':
        this.generateIndexedStore(instr);
        break;

      case 'CALL_INDIRECT':
        this.generateCallIndirect(instr);
        break;

      default:
        console.warn(`Unknown instruction opcode: ${instr.opcode}`);
    }
  }

  /**
    * Generates a LOAD instruction
    * @param {LoadInstruction} instr - Load instruction
    */
    generateLoad(instr) {
      const [dest, src] = instr.operands;

      // Immediate/numeric load
      if (typeof src === 'number' || (typeof src === 'string' && (/^\d+$/.test(src) || src.startsWith('#')))) {
        this.codeLines.push(`  ld hl, ${this.formatValue(src)}`);
        if (dest !== 'hl') {
          if (/^[a-z]$/.test(dest) && ['a','b','c','d','e','h','l'].includes(dest)) {
            // 8-bit physical register - store low byte
            this.codeLines.push(`  ld ${dest}, l`);
          } else {
            // Variable/spill - store 16-bit
            this.codeLines.push(`  ld (${dest}), hl`);
          }
        }
        return;
      }

       // Load from memory address or register
       if (typeof src === 'string') {
         if (src === 'ret_val') {
           // Return value is in A after a call - zero-extend to 16-bit and store
           if (dest !== 'a') {
             this.codeLines.push(`  ld l, a`);
             this.codeLines.push(`  ld h, 0`);
             this.codeLines.push(`  ld (${dest}), hl`);
           }
           return;
         }
         if (src === 'hl') {
           // Source is HL register - copy to dest
           if (dest !== 'hl') {
             this.codeLines.push(`  ld (${dest}), hl`);
           }
         } else if (['a','b','c','d','e'].includes(src)) {
           // Source is 8-bit register - load into HL (low byte only)
           this.codeLines.push(`  ld l, ${src}`);
           this.codeLines.push(`  ld h, 0`);
           if (dest !== 'hl') {
             this.codeLines.push(`  ld (${dest}), hl`);
           }
         } else if (src.startsWith('flt_')) {
           // Float label source - load 4 bytes (IEEE 754 single-precision)
           this.codeLines.push(`  ld hl, (${src})`);    // HL = bytes 0-1
           this.codeLines.push(`  inc hl`);
           this.codeLines.push(`  inc hl`);
           this.codeLines.push(`  ld de, (hl)`);       // DE = bytes 2-3
           if (dest !== 'hl') {
             this.codeLines.push(`  ld (${dest}), hl`);
           }
           return;
          } else {
            // Source is a memory variable/label
            const size = instr.size || 2;
            if (size === 4) {
              // 4-byte load (IEEE 754 single-precision float)
              this.codeLines.push(`  ld hl, (${src})`);    // HL = bytes 0-1
              this.codeLines.push(`  inc hl`);
              this.codeLines.push(`  inc hl`);
              this.codeLines.push(`  ld de, (hl)`);       // DE = bytes 2-3
              if (dest !== 'hl') {
                this.codeLines.push(`  ld (${dest}), hl`);
              }
            } else {
              this.codeLines.push(`  ld hl, (${src})`);
              if (dest !== 'hl') {
                this.codeLines.push(`  ld (${dest}), hl`);
              }
            }
          }
       }
    }

  /**
    * Generates a STORE instruction
    * @param {StoreInstruction} instr - Store instruction
    */
    generateStore(instr) {
      const [dest, src] = instr.operands;
      const size = instr.size || 2;

      if (size === 4 && src === 'hl') {
        // Store 4 bytes from HL+DE to memory (IEEE 754 single-precision, little-endian)
        this.codeLines.push(`  ld hl, (${dest})`);
        this.codeLines.push(`  ld a, e`);
        this.codeLines.push(`  ld (hl), a`);    // byte 0 (low)
        this.codeLines.push(`  inc hl`);
        this.codeLines.push(`  ld a, d`);
        this.codeLines.push(`  ld (hl), a`);    // byte 1
        this.codeLines.push(`  inc hl`);
        this.codeLines.push(`  ld a, l`);
        this.codeLines.push(`  ld (hl), a`);    // byte 2
        this.codeLines.push(`  inc hl`);
        this.codeLines.push(`  ld a, h`);
        this.codeLines.push(`  ld (hl), a`);    // byte 3 (high)
        return;
      }

      // Store HL to memory address
      if (src === 'hl') {
        this.codeLines.push(`  ld (${dest}), hl`);
      } else if (['a','b','c','d','e','h','l'].includes(src)) {
        // 8-bit register - zero-extend to 16-bit then store
        this.codeLines.push(`  ld l, ${src}`);
        this.codeLines.push(`  ld h, 0`);
        this.codeLines.push(`  ld (${dest}), hl`);
      } else {
        // src is a memory variable/label holding 16-bit value
        this.codeLines.push(`  ld hl, (${src})`);
        this.codeLines.push(`  ld (${dest}), hl`);
      }
    }

  /**
   * Generates a binary operation instruction
   * @param {BinaryOpInstruction} instr - Binary op instruction
   */
  generateBinaryOp(instr) {
    const [dest, op, src1, src2] = instr.operands;

    // Comparison operations produce 0 or 1 in A
    const comparisonOps = ['lt', 'gt', 'le', 'ge', 'eq', 'ne', 'land', 'lor'];
    if (comparisonOps.includes(op)) {
      this.generateComparison(instr);
      return;
    }

    // Handle address store operation (used for assignment to computed targets)
    if (op === 'addr') {
      // dest = register holding address to store to
      // src2 = value to store
      this.codeLines.push(`  ld hl, ${dest}`);
      this.codeLines.push(`  ld a, ${src2}`);
      this.codeLines.push(`  ld (hl), a`);
      return;
    }

    // Handle struct member access (fallback opcode)
    if (op === 'member' || op === 'pmember') {
      // dest = result register
      // src1 = base address register
      // src2 = field name (ignored, handled by IR translation)
      // This should not be reached after proper IR translation
      this.codeLines.push(`  ld hl, ${src1}`);
      this.codeLines.push(`  ld a, (hl)`);
      const reg = this.formatRegister(dest, true);
      if (reg !== 'a') {
        this.codeLines.push(`  ld ${reg}, a`);
      }
      return;
    }

    // Handle mov operation (copy value to specific register byte)
    if (op === 'mov') {
      // Handle physical register sources
      if (src1 === 'a') {
        if (dest === 'h') {
          this.codeLines.push(`  ld h, 0`);
        } else if (dest === 'l') {
          this.codeLines.push(`  ld l, a`);
        } else if (dest === 'a') {
          this.codeLines.push(`  ld a, a`);
        } else if (dest === 'b') {
          this.codeLines.push(`  ld b, a`);
        } else if (dest === 'c') {
          this.codeLines.push(`  ld c, a`);
        } else if (dest === 'd') {
          this.codeLines.push(`  ld d, a`);
        } else if (dest === 'e') {
          this.codeLines.push(`  ld e, a`);
        } else {
          this.codeLines.push(`  ld l, a`);
          this.codeLines.push(`  ld h, 0`);
          this.codeLines.push(`  ld (${dest}), hl`);
        }
        return;
      }
      if (src1 === 'hl') {
        if (dest === 'h') {
          this.codeLines.push(`  ld h, h`);
        } else if (dest === 'l') {
          this.codeLines.push(`  ld l, l`);
        } else if (dest === 'a') {
          this.codeLines.push(`  ld a, l`);
        } else if (dest === 'b') {
          this.codeLines.push(`  ld b, l`);
        } else if (dest === 'c') {
          this.codeLines.push(`  ld c, l`);
        } else if (dest === 'd') {
          this.codeLines.push(`  ld d, l`);
        } else if (dest === 'e') {
          this.codeLines.push(`  ld e, l`);
        } else {
          this.codeLines.push(`  ld (${dest}), hl`);
        }
        return;
      }
      // General mov: copy src1 to dest
      this.codeLines.push(`  ld hl, ${src1}`);
      if (dest === 'h') {
        this.codeLines.push(`  ld h, h`);
      } else if (dest === 'l') {
        this.codeLines.push(`  ld l, l`);
      } else if (dest === 'a') {
        this.codeLines.push(`  ld a, l`);
      } else if (dest === 'b') {
        this.codeLines.push(`  ld b, l`);
      } else if (dest === 'c') {
        this.codeLines.push(`  ld c, l`);
      } else if (dest === 'd') {
        this.codeLines.push(`  ld d, l`);
      } else if (dest === 'e') {
        this.codeLines.push(`  ld e, l`);
      } else {
        this.codeLines.push(`  ld (${dest}), hl`);
      }
      return;
    }

    // Handle count operation (constant assignment)
    if (op === 'count') {
      this.codeLines.push(`  ld hl, ${src1}`);
      if (dest !== 'hl') {
        this.codeLines.push(`  ld (${dest}), hl`);
      }
      return;
    }

    // Most Z80 operations work with accumulator (A), so we need to be careful
    this.codeLines.push(`  ld a, ${src1}`);

    switch (op) {
      case 'add':
        this.codeLines.push(`  add a, ${src2}`);
        break;

      case 'sub':
        this.codeLines.push(`  sub ${src2}`);
        break;

      case 'mul':
        this.codeLines.push(`  ld b, a`);
        this.codeLines.push(`  xor a`);
        this.codeLines.push(`  ld c, ${src2}`);
        this.codeLines.push('mul_loop:');
        this.codeLines.push(`  add a, b`);
        this.codeLines.push(`  dec c`);
        this.codeLines.push('  jp nz, mul_loop');
        break;

      case 'div':
        this.codeLines.push(`  ld b, ${src2}`);
        this.codeLines.push(`  ld c, ${src1}`);
        this.codeLines.push(`  ld a, 0`);
        const divLabel = this.label('div');
        this.codeLines.push(`${divLabel}:`);
        this.codeLines.push('  sub b');
        this.codeLines.push('  inc l');
        this.codeLines.push('  ld a, c');
        this.codeLines.push('  cp b');
        this.codeLines.push(`  jp nc, ${divLabel}`);
        this.codeLines.push('  add a, b');
        this.codeLines.push('  ld c, a');
        this.codeLines.push('  dec l');
        this.codeLines.push('  ld a, l');
        break;

      case 'and':
        this.codeLines.push(`  and ${src2}`);
        break;

      case 'or':
        this.codeLines.push(`  or ${src2}`);
        break;

      case 'xor':
        this.codeLines.push(`  xor ${src2}`);
        break;

      case 'shl':
        this.codeLines.push(`  ld b, ${src2}`);
        const shlLabel = this.label('shl');
        this.codeLines.push(`${shlLabel}:`);
        this.codeLines.push('  rl a');
        this.codeLines.push('  dec b');
        this.codeLines.push('  ld a, b');
        this.codeLines.push('  or a');
        this.codeLines.push(`  jp nz, ${shlLabel}`);
        break;

      case 'shr':
        this.codeLines.push(`  ld b, ${src2}`);
        const shrLabel = this.label('shr');
        this.codeLines.push(`${shrLabel}:`);
        this.codeLines.push('  rr a');
        this.codeLines.push('  dec b');
        this.codeLines.push('  ld a, b');
        this.codeLines.push('  or a');
        this.codeLines.push(`  jp nz, ${shrLabel}`);
        break;

      case 'mod':
        this.codeLines.push(`  ld b, ${src2}`);
        this.codeLines.push(`  ld c, ${src1}`);
        this.codeLines.push(`  ld a, 0`);
        const modLabel = this.label('mod');
        this.codeLines.push(`${modLabel}:`);
        this.codeLines.push('  sub b');
        this.codeLines.push('  ld a, c');
        this.codeLines.push('  cp b');
        this.codeLines.push(`  jp nc, ${modLabel}`);
        break;

      default:
        console.warn(`Unknown binary operation: ${op}`);
    }

    // Store result to destination
    const reg = this.formatRegister(dest, true);
    if (reg !== 'a') {
      this.codeLines.push(`  ld ${reg}, a`);
    }
  }

  /**
   * Generates a comparison operation (produces 0 or 1)
   * @param {BinaryOpInstruction} instr - Comparison instruction
   */
  generateComparison(instr) {
    const [dest, op, src1, src2] = instr.operands;
    const falseLabel = this.label('cmp_false');
    const endLabel = this.label('cmp_end');

    this.codeLines.push(`  ld a, ${src1}`);
    this.codeLines.push(`  cp ${src2}`);

    const jumpMap = {
      'eq': 'z', 'ne': 'nz',
      'lt': 'c', 'gt': 'nc',
      'le': 'nc', 'ge': 'z'
    };

    const flag = jumpMap[op];
    if (flag) {
      this.codeLines.push(`  jp ${flag}, ${endLabel}`);
    }

    this.codeLines.push(`${falseLabel}:`);
    this.codeLines.push(`  xor a`);
    this.codeLines.push(`  jp ${endLabel}`);

    this.codeLines.push(`${endLabel}:`);
    this.codeLines.push(`  ld a, 1`);

    const reg = this.formatRegister(dest, true);
    if (reg !== 'a') {
      this.codeLines.push(`  ld ${reg}, a`);
    }
  }

  /**
   * Generates a unique label
   * @param {string} prefix - Label prefix
   * @returns {string} Unique label name
   */
  label(prefix) {
    return `${prefix}_${this.nextTempId++}`;
  }

  /**
   * Generates a unary operation instruction
   * @param {UnaryOpInstruction} instr - Unary op instruction
   */
  generateUnaryOp(instr) {
    const [dest, op, src] = instr.operands;

    // Handle mov operation (copy value to specific register byte)
    if (op === 'mov') {
      // Handle physical register sources
      if (src === 'a') {
        if (dest === 'l') {
          this.codeLines.push(`  ld l, a`);
        } else if (dest === 'a') {
          this.codeLines.push(`  ld a, a`);
        } else if (dest === 'h') {
          this.codeLines.push(`  ld h, 0`);
        } else {
          this.codeLines.push(`  ld l, a`);
          this.codeLines.push(`  ld h, 0`);
          this.codeLines.push(`  ld (${dest}), hl`);
        }
        return;
      }
      if (src === 'hl') {
        if (dest === 'l') {
          this.codeLines.push(`  ld l, l`);
        } else if (dest === 'a') {
          this.codeLines.push(`  ld a, l`);
        } else if (dest === 'h') {
          this.codeLines.push(`  ld h, h`);
        } else {
          this.codeLines.push(`  ld (${dest}), hl`);
        }
        return;
      }
      // General mov: copy src to dest
      this.codeLines.push(`  ld hl, ${src}`);
      if (dest === 'l') {
        this.codeLines.push(`  ld l, l`);
      } else if (dest === 'a') {
        this.codeLines.push(`  ld a, l`);
      } else if (dest === 'h') {
        this.codeLines.push(`  ld h, h`);
      } else {
        this.codeLines.push(`  ld (${dest}), hl`);
      }
      return;
    }

    this.codeLines.push(`  ld a, ${src}`);

    switch (op) {
      case 'neg':
        // Two's complement negation: cpl + 1
        this.codeLines.push('  cpl');
        this.codeLines.push('  inc a');
        break;

      case 'not':
        // One's complement
        this.codeLines.push('  cpl');
        break;

      case 'lognot':
        // Logical not: 0 -> 1, non-zero -> 0
        this.codeLines.push('  cpl');
        this.codeLines.push('  rrca');
        this.codeLines.push('  and #1');
        break;

      default:
        console.warn(`Unknown unary operation: ${op}`);
    }

    const reg = this.formatRegister(dest, true);
    if (reg !== 'a') {
      this.codeLines.push(`  ld ${reg}, a`);
    }
  }

  /**
    * Generates a CALL instruction
    * @param {CallInstruction} instr - Call instruction
    */
    generateCall(instr) {
      const [func, ...args] = instr.operands;
      const callingConvention = instr.callingConvention;
      const calleeFunc = this.currentFunctions?.get(func);
      const paramTypes = calleeFunc?.metadata?.paramTypes || [];

      switch (callingConvention) {
        case CALLING_CONVENTION_CDECL:
          for (const line of this.generateCdeclCall(args, func, paramTypes)) {
            this.codeLines.push(line);
          }
          break;
        case CALLING_CONVENTION_FASTCALL:
          for (const line of this.generateFastcallCall(args, func, paramTypes)) {
            this.codeLines.push(line);
          }
          break;
        case CALLING_CONVENTION_CALLEE:
          for (const line of this.generateCalleeCall(args, func, paramTypes)) {
            this.codeLines.push(line);
          }
          break;
        case CALLING_CONVENTION_NEW_Sdcc:
          for (const line of this.generateNewSdccCall(args, func, paramTypes)) {
            this.codeLines.push(line);
          }
          break;
        default:
          for (const line of this.generateNewSdccCall(args, func, paramTypes)) {
            this.codeLines.push(line);
          }
          break;
      }
    }

    generateCdeclCall(args, funcName, paramTypes = []) {
      const codeLines = [];

      // Args are already pushed by PushInstruction in IR
      codeLines.push(`  call ${funcName}`);

      if (args.length > 0 && !this.isVariadicFunction(funcName)) {
        const bytes = args.length * 2;
        codeLines.push(`  ld hl, sp`);
        codeLines.push(`  ld de, ${bytes}`);
        codeLines.push('  add hl, de');
        codeLines.push('  ld sp, hl');
      }

      return codeLines;
    }

    generateFastcallCall(args, funcName, paramTypes = []) {
      const codeLines = [];

      if (args.length === 1) {
        // Arg is already loaded into L by mov instruction in IR
        codeLines.push(`  call ${funcName}`);
        codeLines.push('  ld a, a');
      } else {
        return this.generateCdeclCall(args, funcName, paramTypes);
      }

      return codeLines;
    }

    generateCalleeCall(args, funcName, paramTypes = []) {
      const codeLines = [];

      // Args are already pushed by PushInstruction in IR
      codeLines.push(`  call ${funcName}`);

      // Callee clears stack - no caller cleanup

      return codeLines;
    }

    generateNewSdccCall(args, funcName, paramTypes = []) {
      const codeLines = [];
      const argTypes = paramTypes.map(p => p?.size || 1);

      // Args are already loaded into registers by mov instructions in IR
      // Spillover args are already pushed by PushInstruction in IR
      codeLines.push(`  call ${funcName}`);

      // Stack cleanup for spillover args (args 3+)
      const spilloverCount = Math.max(0, args.length - 2);
      if (spilloverCount > 0) {
        const bytes = spilloverCount * 2;
        codeLines.push(`  ld hl, sp`);
        codeLines.push(`  ld de, ${bytes}`);
        codeLines.push('  add hl, de');
        codeLines.push('  ld sp, hl');
      }

      // Return value loading (heuristic based on arg types)
      const isFloatReturn = funcName.startsWith('_float_');
      if (isFloatReturn) {
        // A holds result pointer (passed as first arg, still in A after call)
        // Load 4 bytes from pointer: bytes 0-1 into DE, bytes 2-3 into HL
        codeLines.push(`  ld l, a`);
        codeLines.push(`  ld h, 0`);
        codeLines.push(`  ld de, (hl)`);   // DE = bytes 0-1 at result pointer
        codeLines.push(`  inc hl`);
        codeLines.push(`  inc hl`);
        codeLines.push(`  ld hl, (hl)`);   // HL = bytes 2-3 at result pointer+2
      } else if (args.length >= 1 && argTypes[0] === 2) {
        codeLines.push('  ld a, d');
      } else {
        codeLines.push('  ld a, a');
      }

      return codeLines;
    }

  /**
    * Generates a CALL_INDIRECT instruction (call through function pointer)
    * The ptr operand should be a register holding the function address
    * (already loaded by LOAD_ADDR + DEREF_LOAD from translateLoadFunctionPointer)
    * @param {CallIndirectInstruction} instr - Call indirect instruction
    */
    generateCallIndirect(instr) {
      const [ptr, ...args] = instr.operands;
      const callingConvention = instr.callingConvention;

      switch (callingConvention) {
        case CALLING_CONVENTION_CDECL:
        case CALLING_CONVENTION_CALLEE:
          this.generateCdeclCallIndirect(ptr, args, callingConvention);
          break;
        case CALLING_CONVENTION_FASTCALL:
          this.generateFastcallCallIndirect(ptr, args);
          break;
        case CALLING_CONVENTION_NEW_Sdcc:
          this.generateNewSdccCallIndirect(ptr, args);
          break;
        default:
          this.generateNewSdccCallIndirect(ptr, args);
          break;
      }
    }

    generateCdeclCallIndirect(ptr, args, callingConvention) {
      // Args are already pushed by PushInstruction in IR
      this.codeLines.push(`  ld hl, ${ptr}`);
      this.codeLines.push('  call hl');

      if (args.length > 0) {
        const bytes = args.length * 2;
        this.codeLines.push(`  ld hl, sp`);
        this.codeLines.push(`  ld de, ${bytes}`);
        this.codeLines.push('  add hl, de');
        this.codeLines.push('  ld sp, hl');
      }

      this.codeLines.push('  ld a, a');
    }

    generateFastcallCallIndirect(ptr, args) {
      // Args are already pushed by PushInstruction in IR
      this.codeLines.push(`  ld hl, ${ptr}`);
      this.codeLines.push('  call hl');

      if (args.length > 1) {
        const bytes = args.length * 2;
        this.codeLines.push(`  ld hl, sp`);
        this.codeLines.push(`  ld de, ${bytes}`);
        this.codeLines.push('  add hl, de');
        this.codeLines.push('  ld sp, hl');
      }

      this.codeLines.push('  ld a, a');
    }

    generateNewSdccCallIndirect(ptr, args) {
      // Args are already pushed by PushInstruction in IR
      this.codeLines.push(`  ld hl, ${ptr}`);
      this.codeLines.push('  call hl');

      if (args.length > 2) {
        const bytes = (args.length - 2) * 2;
        this.codeLines.push(`  ld hl, sp`);
        this.codeLines.push(`  ld de, ${bytes}`);
        this.codeLines.push('  add hl, de');
        this.codeLines.push('  ld sp, hl');
      }

      this.codeLines.push('  ld a, a');
    }

  /**
     * Checks if a function is variadic (has ellipsis parameter)
     * @param {string} funcName - Function name to check
     * @returns {boolean} True if the function is variadic
     */
    isVariadicFunction(funcName) {
      const func = this.currentFunctions?.get(funcName);
      return func ? func.metadata?.isVariadic : false;
    }

  /**
   * Checks if a name is a Z80 register or temp register name
   * @param {string} name - Name to check
   * @returns {boolean} True if it's a register name
   */
  isRegisterName(name) {
    if (['a', 'b', 'c', 'd', 'e', 'h', 'l', 'af', 'hl', 'de', 'ix', 'iy', 'sp'].includes(name)) return true;
    if (name.startsWith('v_') || name.startsWith('arg')) return true;
    return false;
  }

  /**
   * Generates a RETURN instruction
   * @param {ReturnInstruction} instr - Return instruction
   */
  generateReturn(instr) {
    const [value] = instr.operands;

    if (value && value !== 'null') {
      this.codeLines.push(`  ld a, ${value}`);
    }

    // Restore frame pointer and return
    this.codeLines.push('  pop ix');
    this.codeLines.push('  ret');
  }

  /**
   * Generates a conditional jump instruction
   * @param {JumpIfInstruction} instr - Conditional jump instruction
   */
  generateJumpIf(instr) {
    const [condition, value, target] = instr.operands;

    // Load value into A for comparison
    this.codeLines.push(`  ld a, ${value}`);

    switch (condition) {
      case 'eq':
        this.codeLines.push('  xor a');
        this.codeLines.push(`  jp z, ${target}`);
        break;

      case 'ne':
        this.codeLines.push('  xor a');
        this.codeLines.push(`  jp nz, ${target}`);
        break;

      case 'lt':
        // Less than: value < 0 (signed comparison)
        this.codeLines.push('  cp 0');
        this.codeLines.push(`  jp nc, skip_${target}`);
        this.codeLines.push(`  jp ${target}`);
        this.labelsUsed.add(`skip_${target}`);
        break;

      case 'le':
        // Less or equal: value <= 0
        this.codeLines.push('  cp 0');
        this.codeLines.push(`  jp p, skip_${target}`);
        this.codeLines.push(`  jp ${target}`);
        this.labelsUsed.add(`skip_${target}`);
        break;

      case 'gt':
        // Greater than: value > 0
        this.codeLines.push('  cp 0');
        this.codeLines.push(`  jp m, skip_${target}`);
        this.codeLines.push(`  jp ${target}`);
        this.labelsUsed.add(`skip_${target}`);
        break;

      case 'ge':
        // Greater or equal: value >= 0
        this.codeLines.push('  cp 0');
        this.codeLines.push(`  jp m, skip_${target}`);
        this.codeLines.push(`  jp ${target}`);
        this.labelsUsed.add(`skip_${target}`);
        break;

      default:
        console.warn(`Unknown condition: ${condition}`);
    }
  }

  /**
   * Generates an unconditional jump instruction
   * @param {JumpInstruction} instr - Jump instruction
   */
  generateJump(instr) {
    const [target] = instr.operands;
    this.codeLines.push(`  jp ${target}`);
  }

  /**
   * Generates a stack allocation instruction
   * @param {AllocStackInstruction} instr - Stack allocation instruction
   */
  generateAllocStack(instr) {
    const [bytes] = instr.operands;

    // Allocate space by decrementing SP (Z80 stack grows downward)
    // Use BC as counter since we can't do add hl,sp directly
    if (bytes <= 255) {
      this.codeLines.push(`  ld b, ${bytes}`);
      const loopLabel = this.label('alloc');
      this.codeLines.push(`${loopLabel}:`);
      this.codeLines.push('  dec sp');
      this.codeLines.push('  dec b');
      this.codeLines.push('  ld a, b');
      this.codeLines.push('  or a');
      this.codeLines.push(`  jp nz, ${loopLabel}`);
    } else {
      this.codeLines.push(`  ld hl, ${bytes}`);
      const loopLabel = this.label('alloc');
      this.codeLines.push(`${loopLabel}:`);
      this.codeLines.push('  dec sp');
      this.codeLines.push('  dec l');
      this.codeLines.push('  ld a, l');
      this.codeLines.push('  or a');
      this.codeLines.push('  jr nz, $-10');
      this.codeLines.push('  dec h');
      this.codeLines.push('  ld a, h');
      this.codeLines.push(`  or a`);
      this.codeLines.push(`  jp nz, ${loopLabel}`);
    }
  }

  /**
   * Generates a stack deallocation instruction
   * @param {FreeStackInstruction} instr - Stack deallocation instruction
   */
  generateFreeStack(instr) {
    const [bytes] = instr.operands;

    // Deallocate space by incrementing SP
    if (bytes <= 255) {
      this.codeLines.push(`  ld b, ${bytes}`);
      const loopLabel = this.label('free');
      this.codeLines.push(`${loopLabel}:`);
      this.codeLines.push('  inc sp');
      this.codeLines.push('  dec b');
      this.codeLines.push('  ld a, b');
      this.codeLines.push('  or a');
      this.codeLines.push(`  jp nz, ${loopLabel}`);
    } else {
      this.codeLines.push(`  ld hl, ${bytes}`);
      const loopLabel = this.label('free');
      this.codeLines.push(`${loopLabel}:`);
      this.codeLines.push('  inc sp');
      this.codeLines.push('  dec l');
      this.codeLines.push('  ld a, l');
      this.codeLines.push('  or a');
      this.codeLines.push('  jr nz, $-10');
      this.codeLines.push('  dec h');
      this.codeLines.push('  ld a, h');
      this.codeLines.push(`  or a`);
      this.codeLines.push(`  jp nz, ${loopLabel}`);
    }
  }

  /**
   * Generates a PUSH instruction (for function call arguments)
   * @param {PushInstruction} instr - Push instruction
   */
  generatePush(instr) {
    const [value] = instr.operands;
    
    // Z80 has push/pop for register pairs, not single registers
    this.codeLines.push(`  ld a, ${value}`);
    this.codeLines.push('  push af');
  }

  /**
   * Generates a POP instruction (for function call arguments)
   * @param {PopInstruction} instr - Pop instruction
   */
  generatePop(instr) {
    const [dest] = instr.operands;

    this.codeLines.push('  pop af');
    if (dest !== 'a') {
      const reg = this.formatRegister(dest, true);
      this.codeLines.push(`  ld ${reg}, a`);
    }
  }

  /**
   * Generates a Z80 intrinsic instruction (special opcodes, port access, etc.)
   * @param {IntrinsicInstruction} instr - Intrinsic instruction
   */
  generateIntrinsic(instr) {
    const [name, ...args] = instr.operands;

    switch (name) {
      case 'NOP':
        this.codeLines.push('  nop');
        break;

      case 'HALT':
        this.codeLines.push('  halt');
        break;

      case 'DI':
        this.codeLines.push('  di');
        break;

      case 'EI':
        this.codeLines.push('  ei');
        break;

      case 'EXX':
        this.codeLines.push('  exx');
        break;

      case 'EX_AF_AF':
        this.codeLines.push("  ex af, af'");
        break;

      case 'EX_DE_HL':
        this.codeLines.push('  ex de, hl');
        break;

      case 'IM':
        this.codeLines.push(`  im ${args[0]}`);
        break;

      case 'RETI':
        this.codeLines.push('  reti');
        break;

      case 'RETN':
        this.codeLines.push('  retn');
        break;

      case 'RLD':
        this.codeLines.push('  rld');
        break;

      case 'RRD':
        this.codeLines.push('  rrd');
        break;

      case 'LD_A_R':
        this.codeLines.push('  ld a, r');
        break;

      case 'LD_R_A':
        this.codeLines.push('  ld r, a');
        break;

      case 'IN':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push('  in a, (c)');
        break;

      case 'IN16':
        this.codeLines.push(`  ld bc, ${args[0]}`);
        this.codeLines.push('  in a, (c)');
        break;

      case 'OUT':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push(`  ld b, ${args[1]}`);
        this.codeLines.push('  out (c), b');
        break;

      case 'OUT16':
        this.codeLines.push(`  ld bc, ${args[0]}`);
        this.codeLines.push(`  ld a, ${args[1]}`);
        this.codeLines.push('  out (c), a');
        break;

      case 'INI':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push('  ld b, 1');
        this.codeLines.push('  ini (hl), (c)');
        break;

      case 'OUTI':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push('  ld b, 1');
        this.codeLines.push('  outi (c), (hl)');
        break;

      case 'INIR':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push(`  ld b, ${args[1]}`);
        this.codeLines.push('  inir');
        break;

      case 'OTIR':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push(`  ld b, ${args[1]}`);
        this.codeLines.push('  otir');
        break;

      case 'IND':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push('  ld b, 1');
        this.codeLines.push('  ind (hl), (c)');
        break;

      case 'OUTD':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push('  ld b, 1');
        this.codeLines.push('  outd (c), (hl)');
        break;

      case 'INDR':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push(`  ld b, ${args[1]}`);
        this.codeLines.push('  indr');
        break;

      case 'OTDR':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push(`  ld b, ${args[1]}`);
        this.codeLines.push('  otdr');
        break;

      case 'SETJMP':
        // __setjmp(jmp_buf) - saves execution context to buffer
        // Saves: PC (return address), SP, IX, HL, DE, BC, AF
        // Returns 0 in accumulator
        // jmp_buf is a pointer to memory where context is stored
        // Layout: [PC_lo, PC_hi, SP_lo, SP_hi, IX_lo, IX_hi, HL_lo, HL_hi, DE_lo, DE_hi, BC_lo, BC_hi, AF]
        this.codeLines.push(`  ld hl, ${args[0]}`); // HL = jmp_buf pointer
        this.codeLines.push('  push ix'); // Save IX
        this.codeLines.push('  pop bc'); // BC = old IX
        this.codeLines.push('  ld (hl), c'); // Store IX_lo
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), b'); // Store IX_hi
        this.codeLines.push('  inc hl');
        this.codeLines.push('  push sp'); // Save SP
        this.codeLines.push('  pop de'); // DE = old SP
        this.codeLines.push('  ld (hl), e'); // Store SP_lo
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), d'); // Store SP_hi
        this.codeLines.push('  inc hl');
        this.codeLines.push('  push hl'); // Save current PC (return address)
        this.codeLines.push('  pop hl'); // HL = return address
        this.codeLines.push('  ld (hl), l'); // Store PC_lo
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h'); // Store PC_hi
        this.codeLines.push('  inc hl');
        this.codeLines.push('  push hl'); // Save HL
        this.codeLines.push('  pop de'); // DE = old HL
        this.codeLines.push('  ld (hl), e'); // Store HL_lo
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), d'); // Store HL_hi
        this.codeLines.push('  inc hl');
        this.codeLines.push('  push de'); // Save DE
        this.codeLines.push('  pop bc'); // BC = old DE
        this.codeLines.push('  ld (hl), c'); // Store DE_lo
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), b'); // Store DE_hi
        this.codeLines.push('  inc hl');
        this.codeLines.push('  push bc'); // Save BC
        this.codeLines.push('  pop hl'); // HL = old BC
        this.codeLines.push('  ld (hl), l'); // Store BC_lo
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h'); // Store BC_hi
        this.codeLines.push('  inc hl');
        this.codeLines.push('  push af'); // Save AF
        this.codeLines.push('  pop hl'); // HL = old AF
        this.codeLines.push('  ld (hl), l'); // Store AF_lo (A register)
        this.codeLines.push('  ld a, 0'); // Return 0
        break;

      case 'LONGJMP':
        // __longjmp(jmp_buf, value) - restores execution context
        // Restores: PC, SP, IX, HL, DE, BC, AF
        // Then jumps to saved PC, making setjmp return `value`
        this.codeLines.push(`  ld hl, ${args[0]}`); // HL = jmp_buf pointer
        this.codeLines.push(`  ld de, ${args[1]}`); // DE = return value
        this.codeLines.push('  push ix'); // Save current IX
        this.codeLines.push('  pop bc');
        this.codeLines.push(`  ld bc, (hl)`); // BC = saved IX_lo (we need full IX)
        this.codeLines.push('  inc hl');
        this.codeLines.push('  push hl'); // Save HL
        this.codeLines.push('  pop de');
        this.codeLines.push(`  ld e, (hl)`); // DE_lo = saved IX_hi
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ex de, hl'); // HL = saved IX (full)
        this.codeLines.push('  push hl'); // Restore IX
        this.codeLines.push('  pop ix');
        this.codeLines.push('  inc hl');
        this.codeLines.push(`  ld e, (hl)`); // DE_lo = saved SP_lo
        this.codeLines.push('  inc hl');
        this.codeLines.push(`  ld d, (hl)`); // DE_hi = saved SP_hi
        this.codeLines.push('  ld sp, de'); // Restore SP
        this.codeLines.push('  inc hl');
        this.codeLines.push(`  ld e, (hl)`); // DE_lo = saved PC_lo
        this.codeLines.push('  inc hl');
        this.codeLines.push(`  ld d, (hl)`); // DE_hi = saved PC_hi
        this.codeLines.push(`  ld hl, ${args[1]}`); // HL = return value (for setjmp return)
        this.codeLines.push('  push de'); // Push return address
        this.codeLines.push('  pop hl'); // HL = saved PC
        this.codeLines.push(`  ld de, ${args[1]}`); // DE = return value
        this.codeLines.push('  ex de, hl'); // HL = saved PC, DE = return value
        this.codeLines.push('  push hl'); // Push return address (fake return)
        this.codeLines.push('  ret'); // Return to saved PC (setjmp will return with value in A)
        break;

      case 'ALLOCA':
        // __alloca(size) - allocates on stack, returns pointer to allocated space
        // Allocates 'size' bytes below current SP and returns pointer to the allocation
        this.codeLines.push(`  ld hl, sp`); // HL = current SP
        this.codeLines.push(`  ld de, ${args[0]}`); // DE = size
        this.codeLines.push('  add hl, de'); // HL = SP - size (allocate by moving SP down)
        this.codeLines.push(`  ld sp, hl`); // Set new SP (allocate)
        this.codeLines.push(`  ld hl, sp`); // Return pointer (current SP = top of allocation)
        break;

      case 'FPUTC':
        // Write a character to a FILE stream using write callback
        // Operands: [char_value_reg, file_ptr_reg]
        // Callback calling convention: push args, load callback in HL, push hl + ret, cleanup stack
        this.codeLines.push(`  ld hl, ${args[1]}`); // HL = FILE pointer
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl'); // HL = offset 4 (write callback low byte)
        this.codeLines.push(`  ld a, (hl)`);
        this.codeLines.push('  ld l, a');
        this.codeLines.push('  inc hl');
        this.codeLines.push(`  ld a, (hl)`); // HL = offset 5 (write callback high byte)
        this.codeLines.push('  ld h, a'); // HL = write callback address
        this.codeLines.push(`  ld a, ${args[0]}`); // A = char value
        this.codeLines.push('  push af'); // Push char arg (2 bytes)
        this.codeLines.push(`  ld a, ${args[1]}`); // A = file_ptr low byte
        this.codeLines.push('  push af'); // Push file_ptr arg (2 bytes)
        this.codeLines.push('  push hl'); // Push write callback address
        this.codeLines.push('  ret'); // Indirect call to write callback
        this.codeLines.push('  ld hl, sp'); // Stack cleanup (2 args * 2 bytes = 4)
        this.codeLines.push('  ld de, 4');
        this.codeLines.push('  add hl, de');
        this.codeLines.push('  ld sp, hl');
        break;

      case 'FGETC':
        // Read a character from a FILE stream using read callback
        // Operands: [file_ptr_reg]
        // Callback calling convention: push args, load callback in HL, push hl + ret, cleanup stack
        this.codeLines.push(`  ld hl, ${args[0]}`); // HL = FILE pointer
        this.codeLines.push('  inc hl'); // HL = offset 2 (read callback low byte)
        this.codeLines.push(`  ld a, (hl)`);
        this.codeLines.push('  ld l, a');
        this.codeLines.push('  inc hl');
        this.codeLines.push(`  ld a, (hl)`); // HL = offset 3 (read callback high byte)
        this.codeLines.push('  ld h, a'); // HL = read callback address
        this.codeLines.push(`  ld a, ${args[0]}`); // A = file_ptr low byte
        this.codeLines.push('  push af'); // Push file_ptr arg (2 bytes)
        this.codeLines.push('  push hl'); // Push read callback address
        this.codeLines.push('  ret'); // Indirect call to read callback
        this.codeLines.push('  ld hl, sp'); // Stack cleanup (1 arg * 2 bytes = 2)
        this.codeLines.push('  ld de, 2');
        this.codeLines.push('  add hl, de');
        this.codeLines.push('  ld sp, hl');
        break;

      case 'FEOF':
        // Check EOF using eof callback
        // Operands: [file_ptr_reg]
        // Callback calling convention: push args, load callback in HL, push hl + ret, cleanup stack
        this.codeLines.push(`  ld hl, ${args[0]}`); // HL = FILE pointer
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl'); // HL = offset 8 (eof callback low byte)
        this.codeLines.push(`  ld a, (hl)`);
        this.codeLines.push('  ld l, a');
        this.codeLines.push('  inc hl');
        this.codeLines.push(`  ld a, (hl)`); // HL = offset 9 (eof callback high byte)
        this.codeLines.push('  ld h, a'); // HL = eof callback address
        this.codeLines.push(`  ld a, ${args[0]}`); // A = file_ptr low byte
        this.codeLines.push('  push af'); // Push file_ptr arg (2 bytes)
        this.codeLines.push('  push hl'); // Push eof callback address
        this.codeLines.push('  ret'); // Indirect call to eof callback
        this.codeLines.push('  ld hl, sp'); // Stack cleanup (1 arg * 2 bytes = 2)
        this.codeLines.push('  ld de, 2');
        this.codeLines.push('  add hl, de');
        this.codeLines.push('  ld sp, hl');
        break;

      case 'FERROR':
        // Check error using error callback
        // Operands: [file_ptr_reg]
        // Callback calling convention: push args, load callback in HL, push hl + ret, cleanup stack
        this.codeLines.push(`  ld hl, ${args[0]}`); // HL = FILE pointer
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl'); // HL = offset 10 (error callback low byte)
        this.codeLines.push(`  ld a, (hl)`);
        this.codeLines.push('  ld l, a');
        this.codeLines.push('  inc hl');
        this.codeLines.push(`  ld a, (hl)`); // HL = offset 11 (error callback high byte)
        this.codeLines.push('  ld h, a'); // HL = error callback address
        this.codeLines.push(`  ld a, ${args[0]}`); // A = file_ptr low byte
        this.codeLines.push('  push af'); // Push file_ptr arg (2 bytes)
        this.codeLines.push('  push hl'); // Push error callback address
        this.codeLines.push('  ret'); // Indirect call to error callback
        this.codeLines.push('  ld hl, sp'); // Stack cleanup (1 arg * 2 bytes = 2)
        this.codeLines.push('  ld de, 2');
        this.codeLines.push('  add hl, de');
        this.codeLines.push('  ld sp, hl');
        break;

      case 'FOPEN':
        // Open a filesystem stream
        // Operands: [name_ptr_reg, mode_ptr_reg]
        // Creates FILE struct on stack, sets streamType=0, sets callback pointers to fs functions
        // Callback function names: fs_read, fs_write, fs_close, fs_eof, fs_error, fs_available, fs_flush
        // FILE struct: 18 bytes [streamType(0), flags(1), port(2), read(4), write(6), close(8), eof(10), error(12), available(14), flush(16)]
        this.codeLines.push(`  ld hl, ${args[0]}`); // HL = file name
        this.codeLines.push(`  ld de, ${args[1]}`); // DE = file mode
        this.codeLines.push(`  ld a, ${args[0]}`); // A = name_ptr
        this.codeLines.push('  push af'); // Push name arg
        this.codeLines.push(`  ld a, ${args[1]}`); // A = mode_ptr
        this.codeLines.push('  push af'); // Push mode arg
        this.codeLines.push('  call fopen'); // Call fopen(name, mode) external function
        this.codeLines.push('  ld hl, sp'); // HL = SP after call
        this.codeLines.push('  ld de, 4'); // DE = 4 bytes (2 args * 2 bytes)
        this.codeLines.push('  add hl, de'); // HL = SP + 4 (restore stack)
        this.codeLines.push('  ld sp, hl'); // Restore SP
        this.codeLines.push('  ld hl, sp'); // HL = current SP (top of allocated 18-byte FILE struct)
        this.codeLines.push('  ld (hl), 0'); // streamType = 0 (filesystem) (offset 0)
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), 0'); // flags = 0 (offset 1)
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, fs_read'); // HL = fs_read address (offset 2)
        this.codeLines.push('  ld (hl), l'); // store low byte
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h'); // store high byte
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, fs_write'); // HL = fs_write address (offset 4)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, fs_close'); // HL = fs_close address (offset 6)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, fs_eof'); // HL = fs_eof address (offset 8)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, fs_error'); // HL = fs_error address (offset 10)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, fs_available'); // HL = fs_available address (offset 12)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, fs_flush'); // HL = fs_flush address (offset 14)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  ld a, l'); // Return pointer in A (low byte of SP)
        break;

      case 'FCLOSE':
        // Close a stream using close callback
        // Operands: [file_ptr_reg]
        // Callback calling convention: push args, load callback in HL, push hl + ret, cleanup stack
        this.codeLines.push(`  ld hl, ${args[0]}`); // HL = FILE pointer
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl'); // HL = offset 8 (close callback low byte)
        this.codeLines.push(`  ld a, (hl)`);
        this.codeLines.push('  ld l, a');
        this.codeLines.push('  inc hl');
        this.codeLines.push(`  ld a, (hl)`); // HL = offset 9 (close callback high byte)
        this.codeLines.push('  ld h, a'); // HL = close callback address
        this.codeLines.push(`  ld a, ${args[0]}`); // A = file_ptr low byte
        this.codeLines.push('  push af'); // Push file_ptr arg (2 bytes)
        this.codeLines.push('  push hl'); // Push close callback address
        this.codeLines.push('  ret'); // Indirect call to close callback
        this.codeLines.push('  ld hl, sp'); // Stack cleanup (1 arg * 2 bytes = 2)
        this.codeLines.push('  ld de, 2');
        this.codeLines.push('  add hl, de');
        this.codeLines.push('  ld sp, hl');
        this.codeLines.push('  xor a'); // Return 0 (success)
        break;

      case 'SERIAL_OPEN':
        // Open a serial port
        // Operands: [port_addr_reg]
        // Creates FILE struct on stack, sets streamType=1, stores port address, sets callback pointers
        // FILE struct: 18 bytes [streamType(0), flags(1), port(2), read(4), write(6), close(8), eof(10), error(12), available(14), flush(16)]
        this.codeLines.push(`  ld hl, ${args[0]}`); // HL = port address
        this.codeLines.push('  push hl'); // Push port arg
        this.codeLines.push('  call serial_open'); // Call serial_open external function
        this.codeLines.push('  ld hl, sp'); // HL = SP after call
        this.codeLines.push('  ld de, 2'); // DE = 2 bytes (1 arg)
        this.codeLines.push('  add hl, de'); // HL = SP + 2
        this.codeLines.push('  ld sp, hl'); // Restore SP
        this.codeLines.push('  ld hl, sp'); // HL = current SP (top of allocated 18-byte FILE struct)
        this.codeLines.push('  ld (hl), 1'); // streamType = 1 (serial) (offset 0)
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), 0'); // flags = 0 (offset 1)
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push(`  ld hl, ${args[0]}`); // HL = port address (from original argument)
        this.codeLines.push('  ld (hl), l'); // store port low byte at offset 2
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h'); // store port high byte at offset 3
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, serial_read_cb'); // HL = serial_read_cb address (offset 4)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, serial_write_cb'); // HL = serial_write_cb address (offset 6)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, serial_close_cb'); // HL = serial_close_cb address (offset 8)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, serial_eof_cb'); // HL = serial_eof_cb address (offset 10)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, serial_error_cb'); // HL = serial_error_cb address (offset 12)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, serial_available_cb'); // HL = serial_available_cb address (offset 14)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, serial_flush_cb'); // HL = serial_flush_cb address (offset 16)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  ld a, l'); // Return pointer in A (low byte of SP)
        break;

      case 'SERIAL_CLOSE':
        // Close a serial stream using close callback
        // Operands: [file_ptr_reg]
        // Callback calling convention: push args, load callback in HL, push hl + ret, cleanup stack
        this.codeLines.push(`  ld hl, ${args[0]}`); // HL = FILE pointer
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl'); // HL = offset 8 (close callback low byte)
        this.codeLines.push(`  ld a, (hl)`);
        this.codeLines.push('  ld l, a');
        this.codeLines.push('  inc hl');
        this.codeLines.push(`  ld a, (hl)`); // HL = offset 9 (close callback high byte)
        this.codeLines.push('  ld h, a'); // HL = close callback address
        this.codeLines.push(`  ld a, ${args[0]}`); // A = file_ptr low byte
        this.codeLines.push('  push af'); // Push file_ptr arg (2 bytes)
        this.codeLines.push('  push hl'); // Push close callback address
        this.codeLines.push('  ret'); // Indirect call to close callback
        this.codeLines.push('  ld hl, sp'); // Stack cleanup (1 arg * 2 bytes = 2)
        this.codeLines.push('  ld de, 2');
        this.codeLines.push('  add hl, de');
        this.codeLines.push('  ld sp, hl');
        this.codeLines.push('  xor a'); // Return 0 (success)
        break;

      case 'SERIAL_READ':
        // Read from serial stream using read callback
        // Operands: [file_ptr_reg]
        // Callback calling convention: push args, load callback in HL, push hl + ret, cleanup stack
        this.codeLines.push(`  ld hl, ${args[0]}`); // HL = FILE pointer
        this.codeLines.push('  inc hl'); // HL = offset 4 (read callback low byte)
        this.codeLines.push(`  ld a, (hl)`);
        this.codeLines.push('  ld l, a');
        this.codeLines.push('  inc hl');
        this.codeLines.push(`  ld a, (hl)`); // HL = offset 5 (read callback high byte)
        this.codeLines.push('  ld h, a'); // HL = read callback address
        this.codeLines.push(`  ld a, ${args[0]}`); // A = file_ptr low byte
        this.codeLines.push('  push af'); // Push file_ptr arg (2 bytes)
        this.codeLines.push('  push hl'); // Push read callback address
        this.codeLines.push('  ret'); // Indirect call to read callback
        this.codeLines.push('  ld hl, sp'); // Stack cleanup (1 arg * 2 bytes = 2)
        this.codeLines.push('  ld de, 2');
        this.codeLines.push('  add hl, de');
        this.codeLines.push('  ld sp, hl');
        break;

      case 'SERIAL_WRITE':
        // Write to serial stream using write callback
        // Operands: [char_value_reg, file_ptr_reg]
        // Callback calling convention: push args, load callback in HL, push hl + ret, cleanup stack
        this.codeLines.push(`  ld hl, ${args[1]}`); // HL = FILE pointer
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl'); // HL = offset 6 (write callback low byte)
        this.codeLines.push(`  ld a, (hl)`);
        this.codeLines.push('  ld l, a');
        this.codeLines.push('  inc hl');
        this.codeLines.push(`  ld a, (hl)`); // HL = offset 7 (write callback high byte)
        this.codeLines.push('  ld h, a'); // HL = write callback address
        this.codeLines.push(`  ld a, ${args[0]}`); // A = char value
        this.codeLines.push('  push af'); // Push char arg (2 bytes)
        this.codeLines.push(`  ld a, ${args[1]}`); // A = file_ptr low byte
        this.codeLines.push('  push af'); // Push file_ptr arg (2 bytes)
        this.codeLines.push('  push hl'); // Push write callback address
        this.codeLines.push('  ret'); // Indirect call to write callback
        this.codeLines.push('  ld hl, sp'); // Stack cleanup (2 args * 2 bytes = 4)
        this.codeLines.push('  ld de, 4');
        this.codeLines.push('  add hl, de');
        this.codeLines.push('  ld sp, hl');
        this.codeLines.push(`  ld a, ${args[0]}`); // Return char value in A
        break;

      case 'SERIAL_AVAILABLE':
        // Check available data using available callback
        // Operands: [file_ptr_reg]
        // Callback calling convention: push args, load callback in HL, push hl + ret, cleanup stack
        this.codeLines.push(`  ld hl, ${args[0]}`); // HL = FILE pointer
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl'); // HL = offset 14 (available callback low byte)
        this.codeLines.push(`  ld a, (hl)`);
        this.codeLines.push('  ld l, a');
        this.codeLines.push('  inc hl');
        this.codeLines.push(`  ld a, (hl)`); // HL = offset 15 (available callback high byte)
        this.codeLines.push('  ld h, a'); // HL = available callback address
        this.codeLines.push(`  ld a, ${args[0]}`); // A = file_ptr low byte
        this.codeLines.push('  push af'); // Push file_ptr arg (2 bytes)
        this.codeLines.push('  push hl'); // Push available callback address
        this.codeLines.push('  ret'); // Indirect call to available callback
        this.codeLines.push('  ld hl, sp'); // Stack cleanup (1 arg * 2 bytes = 2)
        this.codeLines.push('  ld de, 2');
        this.codeLines.push('  add hl, de');
        this.codeLines.push('  ld sp, hl');
        break;

      case 'TERMINAL_OPEN':
        // Open a terminal stream
        // Operands: none
        // Creates FILE struct on stack, sets streamType=2, stores device=1 in port field, sets callback pointers
        // FILE struct: 18 bytes [streamType(0), flags(1), port(2), read(4), write(6), close(8), eof(10), error(12), available(14), flush(16)]
        this.codeLines.push('  push hl'); // Save HL
        this.codeLines.push('  call terminal_open'); // Call terminal_open external function
        this.codeLines.push('  pop hl'); // Restore HL
        this.codeLines.push('  ld hl, sp'); // HL = current SP (top of allocated 18-byte FILE struct)
        this.codeLines.push('  ld (hl), 2'); // streamType = 2 (terminal) (offset 0)
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), 0'); // flags = 0 (offset 1)
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, 1'); // device = 1 (primary terminal) (offset 2)
        this.codeLines.push('  ld (hl), l'); // store low byte
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h'); // store high byte (0)
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, terminal_read_cb'); // HL = terminal_read_cb address (offset 4)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, terminal_write_cb'); // HL = terminal_write_cb address (offset 6)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, terminal_close_cb'); // HL = terminal_close_cb address (offset 8)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, terminal_eof_cb'); // HL = terminal_eof_cb address (offset 10)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, terminal_error_cb'); // HL = terminal_error_cb address (offset 12)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, terminal_available_cb'); // HL = terminal_available_cb address (offset 14)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld hl, terminal_flush_cb'); // HL = terminal_flush_cb address (offset 16)
        this.codeLines.push('  ld (hl), l');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  ld (hl), h');
        this.codeLines.push('  ld a, l'); // Return pointer in A (low byte of SP)
        break;

      case 'TERMINAL_CLOSE':
        // Close a terminal stream using close callback
        // Operands: [file_ptr_reg]
        // Callback calling convention: push args, load callback in HL, push hl + ret, cleanup stack
        this.codeLines.push(`  ld hl, ${args[0]}`); // HL = FILE pointer
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl');
        this.codeLines.push('  inc hl'); // HL = offset 8 (close callback low byte)
        this.codeLines.push(`  ld a, (hl)`);
        this.codeLines.push('  ld l, a');
        this.codeLines.push('  inc hl');
        this.codeLines.push(`  ld a, (hl)`); // HL = offset 9 (close callback high byte)
        this.codeLines.push('  ld h, a'); // HL = close callback address
        this.codeLines.push(`  ld a, ${args[0]}`); // A = file_ptr low byte
        this.codeLines.push('  push af'); // Push file_ptr arg (2 bytes)
        this.codeLines.push('  push hl'); // Push close callback address
        this.codeLines.push('  ret'); // Indirect call to close callback
        this.codeLines.push('  ld hl, sp'); // Stack cleanup (1 arg * 2 bytes = 2)
        this.codeLines.push('  ld de, 2');
        this.codeLines.push('  add hl, de');
        this.codeLines.push('  ld sp, hl');
        this.codeLines.push('  xor a'); // Return 0 (success)
        break;

      default:
        console.warn(`Unknown intrinsic: ${name}`);
    }
  }

  /**
    * Generates a LOAD_ADDR instruction (load address of a symbol)
    * @param {LoadAddrInstruction} instr - Load address instruction
    */
   generateLoadAddr(instr) {
     const [dest, src] = instr.operands;
     this.codeLines.push(`  ld hl, ${src}`);
     if (dest !== 'hl') {
       // Store 16-bit address into memory location
       this.codeLines.push(`  ld (${dest}), hl`);
     }
   }

  /**
    * Generates a DEREF_LOAD instruction (load value from pointer address)
    * @param {DerefLoadInstruction} instr - Dereference load instruction
    */
   generateDerefLoad(instr) {
     const [dest, ptr] = instr.operands;
     // ptr can be a physical register (hl) or a memory variable/spill location
     if (ptr === 'hl') {
       this.codeLines.push(`  ld a, (hl)`);
     } else {
       this.codeLines.push(`  ld hl, (${ptr})`);
       this.codeLines.push(`  ld a, (hl)`);
     }
     const reg = this.formatRegister(dest, true);
     if (reg !== 'a') {
       this.codeLines.push(`  ld ${reg}, a`);
     }
   }

  /**
    * Generates a DEREF_STORE instruction (store value to pointer address)
    * @param {DerefStoreInstruction} instr - Dereference store instruction
    */
    generateDerefStore(instr) {
      const [ptr, src] = instr.operands;
      // ptr can be a physical register (hl) or a memory variable/spill location
      if (ptr === 'hl') {
        // Address already in HL
      } else {
        this.codeLines.push(`  ld hl, (${ptr})`);
      }
      // src is a memory location, HL, or 8-bit register holding the value
      if (src === 'hl') {
        // Store 4 bytes from HL+DE (IEEE 754 single-precision, little-endian)
        this.codeLines.push(`  ld a, e`);
        this.codeLines.push(`  ld (hl), a`);    // byte 0 (low)
        this.codeLines.push(`  inc hl`);
        this.codeLines.push(`  ld a, d`);
        this.codeLines.push(`  ld (hl), a`);    // byte 1
        this.codeLines.push(`  inc hl`);
        this.codeLines.push(`  ld a, l`);
        this.codeLines.push(`  ld (hl), a`);    // byte 2
        this.codeLines.push(`  inc hl`);
        this.codeLines.push(`  ld a, h`);
        this.codeLines.push(`  ld (hl), a`);    // byte 3 (high)
      } else if (['a','b','c','d','e','h','l'].includes(src)) {
        // 8-bit register - store byte at address in HL
        this.codeLines.push(`  ld a, ${src}`);
        this.codeLines.push(`  ld (hl), a`);
      } else {
        // src is a memory variable/label holding 16-bit value
        this.codeLines.push(`  ld hl, (${src})`);
        this.codeLines.push(`  ld (hl), l`);
        this.codeLines.push(`  inc hl`);
        this.codeLines.push(`  ld (hl), h`);
      }
    }

  /**
   * Generates an INDEXED_LOAD instruction (array index with element size)
   * @param {IndexedLoadInstruction} instr - Indexed load instruction
   */
   generateIndexedLoad(instr) {
     const [dest, base, index, elemSize] = instr.operands;
     if (elemSize === 1) {
       this.codeLines.push(`  ld hl, ${base}`);
       this.codeLines.push(`  ld e, ${index}`);
       this.codeLines.push(`  ld d, 0`);
       this.codeLines.push(`  add hl, de`);
       this.codeLines.push(`  ld a, (hl)`);
     } else if (elemSize === 2) {
       this.codeLines.push(`  ld hl, ${base}`);
       this.codeLines.push(`  ld de, ${index}`);
       this.codeLines.push(`  add hl, de`);
       this.codeLines.push(`  add hl, de`);
       this.codeLines.push(`  ld a, (hl)`);
     } else if (elemSize === 4) {
       // Float array element - load 4 bytes: bytes 0-1 into DE, bytes 2-3 into HL
       this.codeLines.push(`  ld hl, ${base}`);
       this.codeLines.push(`  ld e, ${index}`);
       this.codeLines.push(`  ld d, 0`);
       this.codeLines.push(`  add hl, de`);
       this.codeLines.push(`  ld de, (hl)`);   // DE = bytes 0-1
       this.codeLines.push(`  inc hl`);
       this.codeLines.push(`  inc hl`);
       this.codeLines.push(`  ld hl, (hl)`);   // HL = bytes 2-3
     } else {
       this.codeLines.push(`  ld hl, ${base}`);
       this.codeLines.push(`  ld de, ${index}`);
       this.codeLines.push(`  add hl, de`);
       const loopLabel = this.label('idx');
       this.codeLines.push(`${loopLabel}:`);
       this.codeLines.push(`  add hl, de`);
       this.codeLines.push(`  dec d`);
       this.codeLines.push(`  ld a, d`);
       this.codeLines.push(`  or a`);
       this.codeLines.push(`  jp nz, ${loopLabel}`);
       this.codeLines.push(`  ld a, (hl)`);
     }
     const reg = this.formatRegister(dest, true);
     if (reg !== 'a') {
       this.codeLines.push(`  ld ${reg}, a`);
     }
   }

  /**
   * Generates an INDEXED_STORE instruction (array index store with element size)
   * @param {IndexedStoreInstruction} instr - Indexed store instruction
   */
   generateIndexedStore(instr) {
     const [base, index, src, elemSize] = instr.operands;
     if (elemSize === 1) {
       this.codeLines.push(`  ld hl, ${base}`);
       this.codeLines.push(`  ld e, ${index}`);
       this.codeLines.push(`  ld d, 0`);
       this.codeLines.push(`  add hl, de`);
     } else if (elemSize === 2) {
       this.codeLines.push(`  ld hl, ${base}`);
       this.codeLines.push(`  ld de, ${index}`);
       this.codeLines.push(`  add hl, de`);
       this.codeLines.push(`  add hl, de`);
     } else if (elemSize === 4) {
       // Float array element - store 4 bytes: bytes 0-1 from DE, bytes 2-3 from HL
       this.codeLines.push(`  ld hl, ${base}`);
       this.codeLines.push(`  ld e, ${index}`);
       this.codeLines.push(`  ld d, 0`);
       this.codeLines.push(`  add hl, de`);
       this.codeLines.push(`  ld a, e`);
       this.codeLines.push(`  ld (hl), a`);    // byte 0 (low)
       this.codeLines.push(`  inc hl`);
       this.codeLines.push(`  ld a, d`);
       this.codeLines.push(`  ld (hl), a`);    // byte 1
       this.codeLines.push(`  inc hl`);
       this.codeLines.push(`  ld a, l`);
       this.codeLines.push(`  ld (hl), a`);    // byte 2
       this.codeLines.push(`  inc hl`);
       this.codeLines.push(`  ld a, h`);
       this.codeLines.push(`  ld (hl), a`);    // byte 3 (high)
     } else {
       this.codeLines.push(`  ld hl, ${base}`);
       this.codeLines.push(`  ld de, ${index}`);
       this.codeLines.push(`  add hl, de`);
       const loopLabel = this.label('idx');
       this.codeLines.push(`${loopLabel}:`);
       this.codeLines.push(`  add hl, de`);
       this.codeLines.push(`  dec d`);
       this.codeLines.push(`  ld a, d`);
       this.codeLines.push(`  or a`);
       this.codeLines.push(`  jp nz, ${loopLabel}`);
     }
     this.codeLines.push(`  ld a, ${src}`);
     this.codeLines.push(`  ld (hl), a`);
   }

  /**
   * Formats a register name for output
   * @param {string} reg - Register identifier
   * @param {boolean} [is8Bit=false] - Whether it's an 8-bit register
   * @returns {string} Formatted register name
   */
  formatRegister(reg, is8Bit = false) {
    const lowerReg = reg.toLowerCase();

    if (lowerReg === 'a' || lowerReg === Registers.A) return 'a';
    if (lowerReg === 'b' || lowerReg === Registers.B) return 'b';
    if (lowerReg === 'c' || lowerReg === Registers.C) return 'c';
    if (lowerReg === 'd' || lowerReg === Registers.D) return 'd';
    if (lowerReg === 'e' || lowerReg === Registers.E) return 'e';
    if (lowerReg === 'h' || lowerReg === Registers.H) return 'h';
    if (lowerReg === 'l' || lowerReg === Registers.L) return 'l';

    // 16-bit registers
    if (lowerReg === 'hl') return 'hl';
    if (lowerReg === Registers.IX) return 'ix';
    if (lowerReg === Registers.IY) return 'iy';
    if (lowerReg === Registers.SP) return 'sp';

    // Temp registers (t0, t1, etc.) - pass through as-is
    if (/^t\d+$/.test(lowerReg)) return lowerReg;

    // Variable names and labels - pass through as-is
    if (/^[a-zA-Z_]\w*$/.test(reg)) return reg;

    throw new Error(`Unknown register: ${reg}`);
  }

  /**
   * Formats a value for output
   * @param {string|number} value - Value to format
   * @returns {string} Formatted value string
   */
  formatValue(value) {
    if (typeof value === 'number') {
      return String(value);
    }

    if (typeof value === 'string') {
      if (/^\d+$/.test(value)) {
        return value;
      }
      // Symbol reference or label
      return value;
    }

    return String(value);
  }

  /**
   * Gets the generated assembly code
   * @returns {string} Assembly source
   */
  getCode() {
    return this.codeLines.join('\n');
  }
}
