/**
 * Z80 Code Generator - transforms IR to Z80 assembly
 */
import { 
  Instruction, BasicBlock, FunctionIR, ProgramIR,
  LoadInstruction, StoreInstruction, BinaryOpInstruction, UnaryOpInstruction,
  CallInstruction, ReturnInstruction, JumpIfInstruction, JumpInstruction,
  LabelInstruction, AllocStackInstruction, FreeStackInstruction, PushInstruction, PopInstruction,
  IntrinsicInstruction, LoadAddrInstruction, DerefLoadInstruction, DerefStoreInstruction,
  IndexedLoadInstruction, IndexedStoreInstruction
} from '../nanopass/il.js';

/**
 * Z80 Register names used in code generation
 */
export const Registers = {
  A: 'a',      // Accumulator (primary)
  B: 'b',      // General purpose register pair BC
  C: 'c',      // General purpose register pair BC
  D: 'd',      // General purpose register pair DE
  E: 'e',      // General purpose register pair DE
  H: 'h',      // General purpose register pair HL
  L: 'l',      // General purpose register pair HL
  IX: 'ix',    // Index register X
  IY: 'iy',    // Index register Y
  SP: 'sp',    // Stack pointer
  PC: 'pc'     // Program counter (implicit)
};

/**
 * Z80 Code Generator class
 */
export class Z80Codegen {
  /**
   * Creates a new Z80 code generator
   * @param {Object} options - Generation options
   */
  constructor(options = {}) {
    this.options = {
      outputDebugInfo: false,
      optimizeStack: true,
      ...options
    };

    this.currentFunction = null;
    this.labelsUsed = new Set();
    this.tempVariables = new Map();
    this.nextTempId = 0;
    
    // Generated assembly code buffer
    this.codeLines = [];
  }

  /**
    * Generates Z80 assembly from a program IR
    * @param {ProgramIR} ir - Program intermediate representation
    * @returns {string} Generated Z80 assembly source
    */
   generate(ir) {
     this.reset();
     
     // Build function lookup map for variadic detection
     this.currentFunctions = new Map();
     if (ir.functions && ir.functions.length > 0) {
       for (const func of ir.functions) {
         this.currentFunctions.set(func.name, func);
       }
     }
     
     // Generate header
     this.generateHeader();

     // Generate global data section
     if (ir.globals && ir.globals.length > 0) {
       this.codeLines.push('');
       this.codeLines.push('; Global Data Section');
       for (const global of ir.globals) {
         this.generateGlobal(global);
       }
     }

     // Generate functions
     if (ir.functions && ir.functions.length > 0) {
       for (const func of ir.functions) {
         this.currentFunction = func;
         this.codeLines.push('');
         this.generateFunction(func);
       }
     }

     return this.codeLines.join('\n') + '\n';
   }

  /**
    * Resets internal state for new code generation
    */
   reset() {
     this.currentFunction = null;
     this.currentFunctions = undefined;
     this.labelsUsed.clear();
     this.tempVariables.clear();
     this.nextTempId = 0;
     this.codeLines = [];
   }

  /**
   * Generates the assembler header/directives
   */
  generateHeader() {
    this.codeLines.push('; Generated by vcc80 - Z80 C Compiler');
    this.codeLines.push('');
    this.codeLines.push('; Entry point (optional)');
    this.codeLines.push('');
  }

  /**
   * Generates a global variable definition
   * @param {Object} global - Global variable descriptor
   */
  generateGlobal(global) {
    const name = global.name;
    
    if (global.type === 'string') {
      this.codeLines.push(`${name}: .db ${global.bytes.join(', ')}`);
    } else if (global.type === 'data') {
      // Data declaration: db, dw
      if (global.value !== undefined) {
        this.codeLines.push(`${name}: .db ${this.formatValue(global.value)}`);
      } else {
        // Reserved space
        const size = global.size || 1;
        this.codeLines.push(`${name}: .ds ${size}`);
      }
    } else if (global.type === 'bss') {
      // Uninitialized data
      this.codeLines.push(`${name}: .ds ${global.size || 1}`);
    } else {
      const size = global.size || 1;
      this.codeLines.push(`${name}: .ds ${size}`);
    }
  }

  /**
   * Generates a complete function definition
   * @param {FunctionIR} func - Function IR
   */
  generateFunction(func) {
    const name = func.name;
    
    this.codeLines.push('');
    this.codeLines.push('; Function: ' + name);
    this.codeLines.push(`${name}:`);

    // Generate prologue if needed (stack setup)
    this.generatePrologue(func);

    // Generate basic blocks in order
    for (const block of func.blocks) {
      this.generateBasicBlock(block);
    }

    // Generate epilogue
    this.generateEpilogue(func);
  }

  /**
   * Generates function prologue (stack frame setup)
   * @param {FunctionIR} func - Function IR
   */
  generatePrologue(func) {
    // Use IX as frame pointer for proper stack frame management
    // Save old IX, set IX = SP, then allocate local space
    this.codeLines.push(`  push ix`);
    this.codeLines.push(`  ld ix, sp`);

    // Calculate total stack space needed from AllocStackInstruction
    let totalSpace = 0;
    for (const block of func.blocks) {
      for (const instr of block.instructions) {
        if (instr instanceof AllocStackInstruction) {
          totalSpace += instr.operands[0];
        }
      }
    }

    if (totalSpace > 0) {
      if (totalSpace <= 255) {
        this.codeLines.push(`  ld b, ${totalSpace}`);
        this.codeLines.push('  dec_sp_loop:');
        this.codeLines.push('  dec sp');
        this.codeLines.push('  dec b');
        this.codeLines.push(`  ld a, b`);
        this.codeLines.push('  or a');
        this.codeLines.push('  jp nz, dec_sp_loop');
      } else {
        this.codeLines.push(`  ld hl, ${totalSpace}`);
        this.codeLines.push('  add hl, sp');
        this.codeLines.push('  ld sp, l');
        this.codeLines.push('  ld sp, h');
      }
    }
  }

  /**
   * Generates function epilogue (stack frame teardown)
   * @param {FunctionIR} func - Function IR
   */
  generateEpilogue(func) {
    // Restore frame pointer and return
    this.codeLines.push('  pop ix');
    this.codeLines.push('  ret');
  }

  /**
   * Generates a basic block of instructions
   * @param {BasicBlock} block - Basic block to generate
   */
  generateBasicBlock(block) {
    // Generate label for the block
    this.codeLines.push(`${block.name}:`);

    for (const instr of block.instructions) {
      this.generateInstruction(instr);
    }

    // Handle implicit fall-through to successor
    const isEntry = block === this.currentFunction.blocks[0];
    if (!isEntry && block.successor) {
      const lastInstr = block.instructions[block.instructions.length - 1];
      if (!(lastInstr instanceof JumpInstruction ||
            lastInstr instanceof JumpIfInstruction ||
            lastInstr instanceof ReturnInstruction)) {
        this.codeLines.push(`  jp ${block.successor.name}`);
      }
    }
  }

  /**
   * Generates a single IL instruction to Z80 assembly
   * @param {Instruction} instr - Instruction to generate
   */
  generateInstruction(instr) {
    switch (instr.opcode) {
      case 'LOAD':
        this.generateLoad(instr);
        break;

      case 'STORE':
        this.generateStore(instr);
        break;

      case 'BINOP':
        this.generateBinaryOp(instr);
        break;

      case 'UNOP':
        this.generateUnaryOp(instr);
        break;

      case 'CALL':
        this.generateCall(instr);
        break;

      case 'RET':
        this.generateReturn(instr);
        break;

      case 'JUMP_IF':
        this.generateJumpIf(instr);
        break;

      case 'JUMP':
        this.generateJump(instr);
        break;

      case 'LABEL':
        // Labels are generated at block level, skip here
        break;

      case 'ALLOC_STACK':
        this.generateAllocStack(instr);
        break;

      case 'FREE_STACK':
        this.generateFreeStack(instr);
        break;

      case 'PUSH':
        this.generatePush(instr);
        break;

      case 'POP':
        this.generatePop(instr);
        break;

      case 'INTRINSIC':
        this.generateIntrinsic(instr);
        break;

      case 'LOAD_ADDR':
        this.generateLoadAddr(instr);
        break;

      case 'DEREF_LOAD':
        this.generateDerefLoad(instr);
        break;

      case 'DEREF_STORE':
        this.generateDerefStore(instr);
        break;

      case 'INDEXED_LOAD':
        this.generateIndexedLoad(instr);
        break;

      case 'INDEXED_STORE':
        this.generateIndexedStore(instr);
        break;

      default:
        console.warn(`Unknown instruction opcode: ${instr.opcode}`);
    }
  }

  /**
   * Generates a LOAD instruction
   * @param {LoadInstruction} instr - Load instruction
   */
  generateLoad(instr) {
    const [dest, src] = instr.operands;

    // Immediate/numeric load
    if (typeof src === 'number' || (typeof src === 'string' && (/^\d+$/.test(src) || src.startsWith('#')))) {
      this.codeLines.push(`  ld hl, ${this.formatValue(src)}`);
      return;
    }

    // Load from memory address into HL
    if (typeof src === 'string' && !dest.startsWith('hl')) {
      this.codeLines.push(`  ld hl, (${src})`);
    } else {
      // Load value to register
      const reg = this.formatRegister(dest);
      this.codeLines.push(`  ld ${reg}, ${this.formatValue(src)}`);
    }
  }

  /**
   * Generates a STORE instruction
   * @param {StoreInstruction} instr - Store instruction
   */
  generateStore(instr) {
    const [dest, src] = instr.operands;

    // Store HL to memory address
    if (src === 'hl') {
      this.codeLines.push(`  ld (${dest}), hl`);
    } else {
      // Load value into HL first
      const reg = this.formatRegister(src);
      this.codeLines.push(`  ld ${reg}, a`); // Assuming src is A register
      this.codeLines.push(`  ld (${dest}), ${reg}`);
    }
  }

  /**
   * Generates a binary operation instruction
   * @param {BinaryOpInstruction} instr - Binary op instruction
   */
  generateBinaryOp(instr) {
    const [dest, op, src1, src2] = instr.operands;

    // Comparison operations produce 0 or 1 in A
    const comparisonOps = ['lt', 'gt', 'le', 'ge', 'eq', 'ne', 'land', 'lor'];
    if (comparisonOps.includes(op)) {
      this.generateComparison(instr);
      return;
    }

    // Most Z80 operations work with accumulator (A), so we need to be careful
    this.codeLines.push(`  ld a, ${src1}`);

    switch (op) {
      case 'add':
        this.codeLines.push(`  add a, ${src2}`);
        break;

      case 'sub':
        this.codeLines.push(`  sub ${src2}`);
        break;

      case 'mul':
        this.codeLines.push(`  ld b, a`);
        this.codeLines.push(`  xor a`);
        this.codeLines.push(`  ld c, ${src2}`);
        this.codeLines.push('mul_loop:');
        this.codeLines.push(`  add a, b`);
        this.codeLines.push(`  dec c`);
        this.codeLines.push('  jp nz, mul_loop');
        break;

      case 'div':
        this.codeLines.push(`  ld b, ${src2}`);
        this.codeLines.push(`  ld c, ${src1}`);
        this.codeLines.push(`  ld a, 0`);
        const divLabel = this.label('div');
        this.codeLines.push(`${divLabel}:`);
        this.codeLines.push('  sub b');
        this.codeLines.push('  inc l');
        this.codeLines.push('  ld a, c');
        this.codeLines.push('  cp b');
        this.codeLines.push(`  jp nc, ${divLabel}`);
        this.codeLines.push('  add a, b');
        this.codeLines.push('  ld c, a');
        this.codeLines.push('  dec l');
        this.codeLines.push('  ld a, l');
        break;

      case 'and':
        this.codeLines.push(`  and ${src2}`);
        break;

      case 'or':
        this.codeLines.push(`  or ${src2}`);
        break;

      case 'xor':
        this.codeLines.push(`  xor ${src2}`);
        break;

      case 'shl':
        this.codeLines.push(`  ld b, ${src2}`);
        const shlLabel = this.label('shl');
        this.codeLines.push(`${shlLabel}:`);
        this.codeLines.push('  rl a');
        this.codeLines.push('  dec b');
        this.codeLines.push('  ld a, b');
        this.codeLines.push('  or a');
        this.codeLines.push(`  jp nz, ${shlLabel}`);
        break;

      case 'shr':
        this.codeLines.push(`  ld b, ${src2}`);
        const shrLabel = this.label('shr');
        this.codeLines.push(`${shrLabel}:`);
        this.codeLines.push('  rr a');
        this.codeLines.push('  dec b');
        this.codeLines.push('  ld a, b');
        this.codeLines.push('  or a');
        this.codeLines.push(`  jp nz, ${shrLabel}`);
        break;

      case 'mod':
        this.codeLines.push(`  ld b, ${src2}`);
        this.codeLines.push(`  ld c, ${src1}`);
        this.codeLines.push(`  ld a, 0`);
        const modLabel = this.label('mod');
        this.codeLines.push(`${modLabel}:`);
        this.codeLines.push('  sub b');
        this.codeLines.push('  ld a, c');
        this.codeLines.push('  cp b');
        this.codeLines.push(`  jp nc, ${modLabel}`);
        break;

      default:
        console.warn(`Unknown binary operation: ${op}`);
    }

    // Store result to destination
    const reg = this.formatRegister(dest, true);
    if (reg !== 'a') {
      this.codeLines.push(`  ld ${reg}, a`);
    }
  }

  /**
   * Generates a comparison operation (produces 0 or 1)
   * @param {BinaryOpInstruction} instr - Comparison instruction
   */
  generateComparison(instr) {
    const [dest, op, src1, src2] = instr.operands;
    const falseLabel = this.label('cmp_false');
    const endLabel = this.label('cmp_end');

    this.codeLines.push(`  ld a, ${src1}`);
    this.codeLines.push(`  cp ${src2}`);

    const jumpMap = {
      'eq': 'z', 'ne': 'nz',
      'lt': 'c', 'gt': 'nc',
      'le': 'nc', 'ge': 'z'
    };

    const flag = jumpMap[op];
    if (flag) {
      this.codeLines.push(`  jp ${flag}, ${endLabel}`);
    }

    this.codeLines.push(`${falseLabel}:`);
    this.codeLines.push(`  xor a`);
    this.codeLines.push(`  jp ${endLabel}`);

    this.codeLines.push(`${endLabel}:`);
    this.codeLines.push(`  ld a, 1`);

    const reg = this.formatRegister(dest, true);
    if (reg !== 'a') {
      this.codeLines.push(`  ld ${reg}, a`);
    }
  }

  /**
   * Generates a unique label
   * @param {string} prefix - Label prefix
   * @returns {string} Unique label name
   */
  label(prefix) {
    return `${prefix}_${this.nextTempId++}`;
  }

  /**
   * Generates a unary operation instruction
   * @param {UnaryOpInstruction} instr - Unary op instruction
   */
  generateUnaryOp(instr) {
    const [dest, op, src] = instr.operands;

    this.codeLines.push(`  ld a, ${src}`);

    switch (op) {
      case 'neg':
        // Two's complement negation: cpl + 1
        this.codeLines.push('  cpl');
        this.codeLines.push('  inc a');
        break;

      case 'not':
        // One's complement
        this.codeLines.push('  cpl');
        break;

      case 'lognot':
        // Logical not: 0 -> 1, non-zero -> 0
        this.codeLines.push('  cpl');
        this.codeLines.push('  rrca');
        this.codeLines.push('  and #1');
        break;

      default:
        console.warn(`Unknown unary operation: ${op}`);
    }

    const reg = this.formatRegister(dest, true);
    if (reg !== 'a') {
      this.codeLines.push(`  ld ${reg}, a`);
    }
  }

  /**
    * Generates a CALL instruction
    * @param {CallInstruction} instr - Call instruction
    */
    generateCall(instr) {
      const [func, ...args] = instr.operands;

      // Push arguments onto stack (right-to-left for Z80 convention)
      for (const arg of args.reverse()) {
        this.codeLines.push(`  ld a, ${arg}`);
        this.codeLines.push('  push af');
      }

      // Perform the call - func can be a label (regular function) or a register (function pointer)
      if (this.isRegisterName(func)) {
        this.codeLines.push('  ld hl, ' + func);
        this.codeLines.push('  call hl');
      } else {
        this.codeLines.push(`  call ${func}`);
      }

      // Clean up stack arguments (each argument pushed as AF = 2 bytes)
      // Variadic functions don't clean up - caller is responsible for cleanup
      if (args.length > 0 && !this.isVariadicFunction(func)) {
        const bytes = args.length * 2;
        this.codeLines.push(`  ld hl, sp`);
        this.codeLines.push(`  ld de, ${bytes}`);
        this.codeLines.push('  add hl, de');
        this.codeLines.push('  ld sp, l');
        this.codeLines.push('  ld sp, h');
      }
    }

  /**
     * Checks if a function is variadic (has ellipsis parameter)
     * @param {string} funcName - Function name to check
     * @returns {boolean} True if the function is variadic
     */
    isVariadicFunction(funcName) {
      const func = this.currentFunctions?.get(funcName);
      return func ? func.metadata?.isVariadic : false;
    }

  /**
   * Checks if a name is a Z80 register or temp register name
   * @param {string} name - Name to check
   * @returns {boolean} True if it's a register name
   */
  isRegisterName(name) {
    if (['a', 'b', 'c', 'd', 'e', 'h', 'l', 'af', 'hl', 'de', 'ix', 'iy', 'sp'].includes(name)) return true;
    if (name.startsWith('v_') || name.startsWith('arg')) return true;
    return false;
  }

  /**
   * Generates a RETURN instruction
   * @param {ReturnInstruction} instr - Return instruction
   */
  generateReturn(instr) {
    const [value] = instr.operands;

    if (value && value !== 'null') {
      this.codeLines.push(`  ld a, ${value}`);
    }

    // Restore frame pointer and return
    this.codeLines.push('  pop ix');
    this.codeLines.push('  ret');
  }

  /**
   * Generates a conditional jump instruction
   * @param {JumpIfInstruction} instr - Conditional jump instruction
   */
  generateJumpIf(instr) {
    const [condition, value, target] = instr.operands;

    // Load value into A for comparison
    this.codeLines.push(`  ld a, ${value}`);

    switch (condition) {
      case 'eq':
        this.codeLines.push('  xor a');
        this.codeLines.push(`  jp z, ${target}`);
        break;

      case 'ne':
        this.codeLines.push('  xor a');
        this.codeLines.push(`  jp nz, ${target}`);
        break;

      case 'lt':
        // Less than: value < 0 (signed comparison)
        this.codeLines.push('  cp 0');
        this.codeLines.push(`  jp nc, skip_${target}`);
        this.codeLines.push(`  jp ${target}`);
        this.labelsUsed.add(`skip_${target}`);
        break;

      case 'le':
        // Less or equal: value <= 0
        this.codeLines.push('  cp 0');
        this.codeLines.push(`  jp p, skip_${target}`);
        this.codeLines.push(`  jp ${target}`);
        this.labelsUsed.add(`skip_${target}`);
        break;

      case 'gt':
        // Greater than: value > 0
        this.codeLines.push('  cp 0');
        this.codeLines.push(`  jp m, skip_${target}`);
        this.codeLines.push(`  jp ${target}`);
        this.labelsUsed.add(`skip_${target}`);
        break;

      case 'ge':
        // Greater or equal: value >= 0
        this.codeLines.push('  cp 0');
        this.codeLines.push(`  jp m, skip_${target}`);
        this.codeLines.push(`  jp ${target}`);
        this.labelsUsed.add(`skip_${target}`);
        break;

      default:
        console.warn(`Unknown condition: ${condition}`);
    }
  }

  /**
   * Generates an unconditional jump instruction
   * @param {JumpInstruction} instr - Jump instruction
   */
  generateJump(instr) {
    const [target] = instr.operands;
    this.codeLines.push(`  jp ${target}`);
  }

  /**
   * Generates a stack allocation instruction
   * @param {AllocStackInstruction} instr - Stack allocation instruction
   */
  generateAllocStack(instr) {
    const [bytes] = instr.operands;

    // Allocate space by decrementing SP (Z80 stack grows downward)
    // Use BC as counter since we can't do add hl,sp directly
    if (bytes <= 255) {
      this.codeLines.push(`  ld b, ${bytes}`);
      const loopLabel = this.label('alloc');
      this.codeLines.push(`${loopLabel}:`);
      this.codeLines.push('  dec sp');
      this.codeLines.push('  dec b');
      this.codeLines.push('  ld a, b');
      this.codeLines.push('  or a');
      this.codeLines.push(`  jp nz, ${loopLabel}`);
    } else {
      this.codeLines.push(`  ld hl, ${bytes}`);
      const loopLabel = this.label('alloc');
      this.codeLines.push(`${loopLabel}:`);
      this.codeLines.push('  dec sp');
      this.codeLines.push('  dec l');
      this.codeLines.push('  ld a, l');
      this.codeLines.push('  or a');
      this.codeLines.push('  jr nz, $-10');
      this.codeLines.push('  dec h');
      this.codeLines.push('  ld a, h');
      this.codeLines.push(`  or a`);
      this.codeLines.push(`  jp nz, ${loopLabel}`);
    }
  }

  /**
   * Generates a stack deallocation instruction
   * @param {FreeStackInstruction} instr - Stack deallocation instruction
   */
  generateFreeStack(instr) {
    const [bytes] = instr.operands;

    // Deallocate space by incrementing SP
    if (bytes <= 255) {
      this.codeLines.push(`  ld b, ${bytes}`);
      const loopLabel = this.label('free');
      this.codeLines.push(`${loopLabel}:`);
      this.codeLines.push('  inc sp');
      this.codeLines.push('  dec b');
      this.codeLines.push('  ld a, b');
      this.codeLines.push('  or a');
      this.codeLines.push(`  jp nz, ${loopLabel}`);
    } else {
      this.codeLines.push(`  ld hl, ${bytes}`);
      const loopLabel = this.label('free');
      this.codeLines.push(`${loopLabel}:`);
      this.codeLines.push('  inc sp');
      this.codeLines.push('  dec l');
      this.codeLines.push('  ld a, l');
      this.codeLines.push('  or a');
      this.codeLines.push('  jr nz, $-10');
      this.codeLines.push('  dec h');
      this.codeLines.push('  ld a, h');
      this.codeLines.push(`  or a`);
      this.codeLines.push(`  jp nz, ${loopLabel}`);
    }
  }

  /**
   * Generates a PUSH instruction (for function call arguments)
   * @param {PushInstruction} instr - Push instruction
   */
  generatePush(instr) {
    const [value] = instr.operands;
    
    // Z80 has push/pop for register pairs, not single registers
    this.codeLines.push(`  ld a, ${value}`);
    this.codeLines.push('  push af');
  }

  /**
   * Generates a POP instruction (for function call arguments)
   * @param {PopInstruction} instr - Pop instruction
   */
  generatePop(instr) {
    const [dest] = instr.operands;

    this.codeLines.push('  pop af');
    if (dest !== 'a') {
      const reg = this.formatRegister(dest, true);
      this.codeLines.push(`  ld ${reg}, a`);
    }
  }

  /**
   * Generates a Z80 intrinsic instruction (special opcodes, port access, etc.)
   * @param {IntrinsicInstruction} instr - Intrinsic instruction
   */
  generateIntrinsic(instr) {
    const [name, ...args] = instr.operands;

    switch (name) {
      case 'NOP':
        this.codeLines.push('  nop');
        break;

      case 'HALT':
        this.codeLines.push('  halt');
        break;

      case 'DI':
        this.codeLines.push('  di');
        break;

      case 'EI':
        this.codeLines.push('  ei');
        break;

      case 'EXX':
        this.codeLines.push('  exx');
        break;

      case 'EX_AF_AF':
        this.codeLines.push("  ex af, af'");
        break;

      case 'EX_DE_HL':
        this.codeLines.push('  ex de, hl');
        break;

      case 'IM':
        this.codeLines.push(`  im ${args[0]}`);
        break;

      case 'RETI':
        this.codeLines.push('  reti');
        break;

      case 'RETN':
        this.codeLines.push('  retn');
        break;

      case 'RLD':
        this.codeLines.push('  rld');
        break;

      case 'RRD':
        this.codeLines.push('  rrd');
        break;

      case 'LD_A_R':
        this.codeLines.push('  ld a, r');
        break;

      case 'LD_R_A':
        this.codeLines.push('  ld r, a');
        break;

      case 'IN':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push('  in a, (c)');
        break;

      case 'IN16':
        this.codeLines.push(`  ld bc, ${args[0]}`);
        this.codeLines.push('  in a, (c)');
        break;

      case 'OUT':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push(`  ld b, ${args[1]}`);
        this.codeLines.push('  out (c), b');
        break;

      case 'OUT16':
        this.codeLines.push(`  ld bc, ${args[0]}`);
        this.codeLines.push(`  ld a, ${args[1]}`);
        this.codeLines.push('  out (c), a');
        break;

      case 'INI':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push('  ld b, 1');
        this.codeLines.push('  ini (hl), (c)');
        break;

      case 'OUTI':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push('  ld b, 1');
        this.codeLines.push('  outi (c), (hl)');
        break;

      case 'INIR':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push(`  ld b, ${args[1]}`);
        this.codeLines.push('  inir');
        break;

      case 'OTIR':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push(`  ld b, ${args[1]}`);
        this.codeLines.push('  otir');
        break;

      case 'IND':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push('  ld b, 1');
        this.codeLines.push('  ind (hl), (c)');
        break;

      case 'OUTD':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push('  ld b, 1');
        this.codeLines.push('  outd (c), (hl)');
        break;

      case 'INDR':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push(`  ld b, ${args[1]}`);
        this.codeLines.push('  indr');
        break;

      case 'OTDR':
        this.codeLines.push(`  ld c, ${args[0]}`);
        this.codeLines.push(`  ld b, ${args[1]}`);
        this.codeLines.push('  otdr');
        break;

      default:
        console.warn(`Unknown intrinsic: ${name}`);
    }
  }

  /**
   * Generates a LOAD_ADDR instruction (load address of a symbol)
   * @param {LoadAddrInstruction} instr - Load address instruction
   */
  generateLoadAddr(instr) {
    const [dest, src] = instr.operands;
    this.codeLines.push(`  ld hl, ${src}`);
    if (dest !== 'hl') {
      this.codeLines.push(`  ex de, hl`);
      this.codeLines.push(`  ld ${dest}, de`);
    }
  }

  /**
   * Generates a DEREF_LOAD instruction (load value from pointer address)
   * @param {DerefLoadInstruction} instr - Dereference load instruction
   */
  generateDerefLoad(instr) {
    const [dest, ptr] = instr.operands;
    this.codeLines.push(`  ld hl, ${ptr}`);
    this.codeLines.push(`  ld a, (hl)`);
    const reg = this.formatRegister(dest, true);
    if (reg !== 'a') {
      this.codeLines.push(`  ld ${reg}, a`);
    }
  }

  /**
   * Generates a DEREF_STORE instruction (store value to pointer address)
   * @param {DerefStoreInstruction} instr - Dereference store instruction
   */
  generateDerefStore(instr) {
    const [ptr, src] = instr.operands;
    this.codeLines.push(`  ld hl, ${ptr}`);
    this.codeLines.push(`  ld a, ${src}`);
    this.codeLines.push(`  ld (hl), a`);
  }

  /**
   * Generates an INDEXED_LOAD instruction (array index with element size)
   * @param {IndexedLoadInstruction} instr - Indexed load instruction
   */
  generateIndexedLoad(instr) {
    const [dest, base, index, elemSize] = instr.operands;
    if (elemSize === 1) {
      this.codeLines.push(`  ld hl, ${base}`);
      this.codeLines.push(`  ld e, ${index}`);
      this.codeLines.push(`  ld d, 0`);
      this.codeLines.push(`  add hl, de`);
      this.codeLines.push(`  ld a, (hl)`);
    } else if (elemSize === 2) {
      this.codeLines.push(`  ld hl, ${base}`);
      this.codeLines.push(`  ld de, ${index}`);
      this.codeLines.push(`  add hl, de`);
      this.codeLines.push(`  add hl, de`);
      this.codeLines.push(`  ld a, (hl)`);
    } else {
      this.codeLines.push(`  ld hl, ${base}`);
      this.codeLines.push(`  ld de, ${index}`);
      this.codeLines.push(`  add hl, de`);
      const loopLabel = this.label('idx');
      this.codeLines.push(`${loopLabel}:`);
      this.codeLines.push(`  add hl, de`);
      this.codeLines.push(`  dec d`);
      this.codeLines.push(`  ld a, d`);
      this.codeLines.push(`  or a`);
      this.codeLines.push(`  jp nz, ${loopLabel}`);
      this.codeLines.push(`  ld a, (hl)`);
    }
    const reg = this.formatRegister(dest, true);
    if (reg !== 'a') {
      this.codeLines.push(`  ld ${reg}, a`);
    }
  }

  /**
   * Generates an INDEXED_STORE instruction (array index store with element size)
   * @param {IndexedStoreInstruction} instr - Indexed store instruction
   */
  generateIndexedStore(instr) {
    const [base, index, src, elemSize] = instr.operands;
    if (elemSize === 1) {
      this.codeLines.push(`  ld hl, ${base}`);
      this.codeLines.push(`  ld e, ${index}`);
      this.codeLines.push(`  ld d, 0`);
      this.codeLines.push(`  add hl, de`);
    } else if (elemSize === 2) {
      this.codeLines.push(`  ld hl, ${base}`);
      this.codeLines.push(`  ld de, ${index}`);
      this.codeLines.push(`  add hl, de`);
      this.codeLines.push(`  add hl, de`);
    } else {
      this.codeLines.push(`  ld hl, ${base}`);
      this.codeLines.push(`  ld de, ${index}`);
      this.codeLines.push(`  add hl, de`);
      const loopLabel = this.label('idx');
      this.codeLines.push(`${loopLabel}:`);
      this.codeLines.push(`  add hl, de`);
      this.codeLines.push(`  dec d`);
      this.codeLines.push(`  ld a, d`);
      this.codeLines.push(`  or a`);
      this.codeLines.push(`  jp nz, ${loopLabel}`);
    }
    this.codeLines.push(`  ld a, ${src}`);
    this.codeLines.push(`  ld (hl), a`);
  }

  /**
   * Formats a register name for output
   * @param {string} reg - Register identifier
   * @param {boolean} [is8Bit=false] - Whether it's an 8-bit register
   * @returns {string} Formatted register name
   */
  formatRegister(reg, is8Bit = false) {
    const lowerReg = reg.toLowerCase();

    if (lowerReg === 'a' || lowerReg === Registers.A) return 'a';
    if (lowerReg === 'b' || lowerReg === Registers.B) return 'b';
    if (lowerReg === 'c' || lowerReg === Registers.C) return 'c';
    if (lowerReg === 'd' || lowerReg === Registers.D) return 'd';
    if (lowerReg === 'e' || lowerReg === Registers.E) return 'e';
    if (lowerReg === 'h' || lowerReg === Registers.H) return 'h';
    if (lowerReg === 'l' || lowerReg === Registers.L) return 'l';

    // 16-bit registers
    if (lowerReg === 'hl') return 'hl';
    if (lowerReg === Registers.IX) return 'ix';
    if (lowerReg === Registers.IY) return 'iy';
    if (lowerReg === Registers.SP) return 'sp';

    // Temp registers (t0, t1, etc.) - pass through as-is
    if (/^t\d+$/.test(lowerReg)) return lowerReg;

    // Variable names and labels - pass through as-is
    if (/^[a-zA-Z_]\w*$/.test(reg)) return reg;

    throw new Error(`Unknown register: ${reg}`);
  }

  /**
   * Formats a value for output
   * @param {string|number} value - Value to format
   * @returns {string} Formatted value string
   */
  formatValue(value) {
    if (typeof value === 'number') {
      return String(value);
    }

    if (typeof value === 'string') {
      if (/^\d+$/.test(value)) {
        return value;
      }
      // Symbol reference or label
      return value;
    }

    return String(value);
  }

  /**
   * Gets the generated assembly code
   * @returns {string} Assembly source
   */
  getCode() {
    return this.codeLines.join('\n');
  }
}
