/**
 * WLA DX compatible assembly code generator
 * Generates assembly source code in WLA DX format for Z80
 */

/**
 * WLA DX section type mapping
 */
export const WlaDxSectionType = {
  code: 'ROM',
  data: 'WRAM',
  bss: 'WRAM',
  rodata: 'ROM'
};

/**
 * Z80 opcode names for disassembly in WLA DX output
 */
export const Z80Opcodes = {
  '0x00': 'nop',
  '0x01': 'ld bc, ##',
  '0x03': 'inc bc',
  '0x04': 'inc b',
  '0x05': 'dec b',
  '0x06': 'ld b, #',
  '0x07': 'rlca',
  '0x08': 'ld (#nn), bc',
  '0x09': 'add hl, bc',
  '0x0a': 'ld a, (#bc)',
  '0x0b': 'dec bc',
  '0x0c': 'inc c',
  '0x0d': 'dec c',
  '0x0e': 'ld c, #',
  '0x0f': 'rrca',
  '0x10': 'stop 0',
  '0x11': 'ld de, ##',
  '0x13': 'inc de',
  '0x14': 'inc d',
  '0x15': 'dec d',
  '0x16': 'ld d, #',
  '0x17': 'rla',
  '0x18': 'jr #',
  '0x19': 'add hl, de',
  '0x1a': 'ld a, (#de)',
  '0x1b': 'dec de',
  '0x1c': 'inc e',
  '0x1d': 'dec e',
  '0x1e': 'ld e, #',
  '0x1f': 'rra',
  '0x20': 'jr nz, #',
  '0x21': 'ld hl, ##',
  '0x23': 'inc hl',
  '0x24': 'inc h',
  '0x25': 'dec h',
  '0x26': 'ld h, #',
  '0x27': 'daa',
  '0x28': 'jr z, #',
  '0x29': 'add hl, hl',
  '0x2a': 'ld a, (#nn)',
  '0x2b': 'dec hl',
  '0x2c': 'inc l',
  '0x2d': 'dec l',
  '0x2e': 'ld l, #',
  '0x2f': 'cpl',
  '0x30': 'jr nc, #',
  '0x31': 'ld sp, ##',
  '0x33': 'inc sp',
  '0x34': 'inc (#hl)',
  '0x35': 'dec (#hl)',
  '0x36': 'ld (#hl), #',
  '0x37': 'scf',
  '0x38': 'jr c, #',
  '0x39': 'ld hl, sp',
  '0x3a': 'ld a, (#nn)',
  '0x3b': 'dec sp',
  '0x3c': 'inc a',
  '0x3d': 'dec a',
  '0x3e': 'ld a, #',
  '0x3f': 'ccf',
  '0x40': 'ld b, b',
  '0x41': 'ld b, c',
  '0x48': 'ld b, h',
  '0x49': 'ld b, l',
  '0x4a': 'ld b, (#hl)',
  '0x4b': 'ld b, (#de)',
  '0x77': 'ld (#hl), a',
  '0x78': 'ld a, a',
  '0x7a': 'ld a, (#hl)',
  '0x7d': 'ld a, l',
  '0x7e': 'ld a, (#hl)',
  '0x80': 'add a, b',
  '0x87': 'add a, a',
  '0x88': 'adc a, b',
  '0x89': 'add a, l',
  '0x8f': 'sub l',
  '0x90': 'adc a, b',
  '0x98': 'sbc a, b',
  '0x99': 'sbc a, l',
  '0xa0': 'and b',
  '0xa7': 'and a',
  '0xaa': 'and (#de)',
  '0xae': 'xor (#hl)',
  '0xb0': 'or b',
  '0xb2': 'or d',
  '0xb7': 'or a',
  '0xb8': 'cp b',
  '0xbe': 'cp (#hl)',
  '0xbf': 'cp a',
  '0xc3': 'jp ##',
  '0xc9': 'ret',
  '0xcd': 'call ##',
  '0xd1': 'pop de',
  '0xdd': 'exx',
  '0xe1': 'pop hl',
  '0xf1': 'pop af',
  '0xf5': 'push af',
  '0xf9': 'ld sp, hl',
  '0xfb': 'ei'
};

/**
 * WLA DX code generator for Z80 assembly output
 */
export class WlaDxCodegen {
  /**
   * Creates a new WLA DX code generator
   * @param {Object} [options] - Generation options
   */
  constructor(options = {}) {
    this.options = {
      commentHeader: true,
      includeMapFile: false,
      ...options
    };
    this.lines = [];
    this.symbolCounter = 0;
  }

  /**
   * Generates WLA DX assembly from an array of object files
   * @param {ObjectFile[]} objectFiles - Array of object files to assemble
   * @returns {string} WLA DX assembly source code
   */
  generate(objectFiles) {
    this.lines = [];

    if (this.options.commentHeader) {
      this.emitComment('Generated by vcc80 - Z80 C Compiler');
      this.emitComment('Target: WLA DX assembler for Z80');
      this.emitComment('');
    }

    this.emitLine('OPTION ROMSIZE $10000');
    this.emitLine('OPTION RAMSIZE $8000');
    this.emitLine('');

    const mergedSections = this.mergeSections(objectFiles);
    const allSymbols = this.collectSymbols(objectFiles);

    for (const [sectionName, sectionData] of mergedSections) {
      this.emitSection(sectionName, sectionData.type, sectionData.contents, sectionData.relocations);
    }

    this.emitLine('');
    this.emitLine('END START');

    return this.lines.join('\n') + '\n';
  }

  /**
   * Merges sections from multiple object files
   * @param {ObjectFile[]} objectFiles - Object files to merge
   * @returns {Map<string, Object>} Merged section data
   */
  mergeSections(objectFiles) {
    const sections = new Map();

    for (const objFile of objectFiles) {
      for (const section of objFile.sections) {
        if (!sections.has(section.name)) {
          sections.set(section.name, {
            type: section.type,
            contents: new Uint8Array(0),
            relocations: []
          });
        }

        const merged = sections.get(section.name);
        const newContents = new Uint8Array(merged.contents.length + section.contents.length);
        newContents.set(merged.contents);
        newContents.set(section.contents, merged.contents.length);
        merged.contents = newContents;

        for (const reloc of section.relocations) {
          const adjustedReloc = {
            ...reloc,
            offset: reloc.offset + merged.contents.length
          };
          merged.relocations.push(adjustedReloc);
        }
      }
    }

    return sections;
  }

  /**
   * Collects all symbols from object files
   * @param {ObjectFile[]} objectFiles - Object files to collect symbols from
   * @returns {Map<string, Object>} Symbol table
   */
  collectSymbols(objectFiles) {
    const symbols = new Map();

    for (const objFile of objectFiles) {
      for (const symbol of objFile.symbols) {
        symbols.set(symbol.name, symbol);
      }
    }

    return symbols;
  }

  /**
   * Emits a section directive and its contents
   * @param {string} name - Section name
   * @param {string} type - Section type
   * @param {Uint8Array} contents - Raw byte contents
   * @param {Object[]} relocations - Relocations for this section
   */
  emitSection(name, type, contents, relocations) {
    const wlaType = WlaDxSectionType[type] || 'ROM';

    this.emitLine(`SECTION "${name}", ${wlaType}`);

    if (relocations.length > 0) {
      this.emitRawBytesWithRelocations(contents, relocations);
      return;
    }

    if (contents.length > 0) {
      const bytesPerLine = 16;
      for (let i = 0; i < contents.length; i += bytesPerLine) {
        const chunk = contents.slice(i, i + bytesPerLine);
        const hexValues = Array.from(chunk).map(b => '$' + b.toString(16).padStart(2, '0').toUpperCase());
        this.emitLine(`  DB ${hexValues.join(', ')}`);
      }
    }
  }

  /**
   * Emits raw bytes with relocation placeholders
   * @param {Uint8Array} contents - Raw byte contents
   * @param {Object[]} relocations - Relocations for this section
   */
  emitRawBytesWithRelocations(contents, relocations) {
    const relocOffsets = new Set(relocations.map(r => r.offset));

    const bytesPerLine = 16;
    for (let i = 0; i < contents.length; i += bytesPerLine) {
      const chunk = contents.slice(i, i + bytesPerLine);
      const values = [];

      for (let j = 0; j < chunk.length; j++) {
        const absOffset = i + j;
        if (relocOffsets.has(absOffset)) {
          const reloc = relocations.find(r => r.offset === absOffset);
          values.push(this.formatRelocation(reloc));
        } else {
          values.push('$' + chunk[j].toString(16).padStart(2, '0').toUpperCase());
        }
      }

      this.emitLine(`  DB ${values.join(', ')}`);
    }
  }

  /**
   * Formats a relocation as a WLA DX expression
   * @param {Object} reloc - Relocation data
   * @returns {string} WLA DX expression string
   */
  formatRelocation(reloc) {
    switch (reloc.type) {
      case 'call':
      case 'jp':
        return `${reloc.symbolName}`;
      case 'abs8':
        return `LOWORD(${reloc.symbolName})`;
      case 'abs16':
        return `HIGHORD(${reloc.symbolName})`;
      case 'pcrel8':
        return `LOWORD(${reloc.symbolName} - *)`;
      default:
        return `$00`;
    }
  }

  /**
   * Emits a comment line
   * @param {string} text - Comment text
   */
  emitComment(text) {
    this.emitLine(`; ${text}`);
  }

  /**
   * Emits a single line of assembly
   * @param {string} line - Assembly line
   */
  emitLine(line) {
    this.lines.push(line);
  }

  /**
   * Generates a label name
   * @param {string} prefix - Label prefix
   * @returns {string} Unique label name
   */
  label(prefix) {
    return `${prefix}_${this.symbolCounter++}`;
  }

  /**
   * Generates WLA DX assembly from raw Z80 bytes with labels
   * @param {Object} config - Configuration object
   * @param {string} config.sectionName - Section name
   * @param {string} config.sectionType - Section type
   * @param {Uint8Array} config.bytes - Raw Z80 bytes
   * @param {Object[]} [config.labels] - Label definitions
   * @param {Object[]} [config.data] - Data definitions
   * @returns {string} WLA DX assembly source
   */
  generateFromConfig(config) {
    this.lines = [];

    if (this.options.commentHeader) {
      this.emitComment('Generated by vcc80 - Z80 C Compiler');
      this.emitComment('Target: WLA DX assembler for Z80');
      this.emitComment('');
    }

    this.emitLine('OPTION ROMSIZE $10000');
    this.emitLine('OPTION RAMSIZE $8000');
    this.emitLine('');

    const sectionType = WlaDxSectionType[config.sectionType] || 'ROM';
    this.emitLine(`SECTION "${config.sectionName}", ${sectionType}`);
    this.emitLine('');

    if (config.labels && config.labels.length > 0) {
      for (const label of config.labels) {
        this.emitLine(`${label.name}:`);
        if (label.value !== undefined) {
          this.emitLine(`  EQU ${label.value}`);
        }
      }
      this.emitLine('');
    }

    if (config.bytes && config.bytes.length > 0) {
      this.emitBytes(config.bytes);
      this.emitLine('');
    }

    if (config.data && config.data.length > 0) {
      for (const data of config.data) {
        this.emitData(data);
      }
      this.emitLine('');
    }

    this.emitLine('END START');

    return this.lines.join('\n') + '\n';
  }

  /**
   * Emits raw bytes as DB directives
   * @param {Uint8Array} bytes - Bytes to emit
   */
  emitBytes(bytes) {
    const bytesPerLine = 16;
    for (let i = 0; i < bytes.length; i += bytesPerLine) {
      const chunk = bytes.slice(i, i + bytesPerLine);
      const hexValues = Array.from(chunk).map(b => '$' + b.toString(16).padStart(2, '0').toUpperCase());
      this.emitLine(`  DB ${hexValues.join(', ')}`);
    }
  }

  /**
   * Emits a data definition
   * @param {Object} data - Data definition
   */
  emitData(data) {
    switch (data.kind) {
      case 'byte':
        this.emitLine(`  DB ${this.formatValue(data.value)}`);
        break;
      case 'word':
        this.emitLine(`  DW ${this.formatValue(data.value)}`);
        break;
      case 'string':
        this.emitLine(`  DB "${data.value}", 0`);
        break;
      case 'reserve':
        this.emitLine(`  DS ${data.size || 1}`);
        break;
      case 'fill':
        this.emitLine(`  DS ${data.count}, ${this.formatValue(data.value)}`);
        break;
      default:
        this.emitLine(`  DB ${this.formatValue(data.value)}`);
        break;
    }
  }

  /**
   * Formats a value for WLA DX output
   * @param {string|number} value - Value to format
   * @returns {string} Formatted value
   */
  formatValue(value) {
    if (typeof value === 'number') {
      if (value < 0) {
        return `-$${Math.abs(value).toString(16).toUpperCase()}`;
      }
      return `$${value.toString(16).toUpperCase()}`;
    }

    if (typeof value === 'string') {
      if (value.startsWith('$')) {
        return value;
      }
      if (/^[0-9]+$/.test(value)) {
        return `$${parseInt(value).toString(16).toUpperCase()}`;
      }
      return value;
    }

    return String(value);
  }

  /**
   * Generates a complete WLA DX project with multiple source files
   * @param {Object} project - Project configuration
   * @param {ObjectFile[]} project.files - Object files
   * @param {string} [project.entryPoint] - Entry point label
   * @param {Object} [project.memoryMap] - Memory map configuration
   * @returns {string} WLA DX assembly source
   */
  generateProject(project) {
    this.lines = [];

    if (this.options.commentHeader) {
      this.emitComment('Generated by vcc80 - Z80 C Compiler');
      this.emitComment('Target: WLA DX assembler for Z80');
      this.emitComment('Project: ' + (project.name || 'unnamed'));
      this.emitComment('');
    }

    this.emitLine('OPTION ROMSIZE $10000');
    this.emitLine('OPTION RAMSIZE $8000');
    this.emitLine('');

    const entryPoint = project.entryPoint || 'START';

    const codeSections = [];
    const dataSections = [];
    const bssSections = [];
    const rodataSections = [];

    for (const objFile of project.files) {
      for (const section of objFile.sections) {
        switch (section.type) {
          case 'code':
            codeSections.push({ objFile, section });
            break;
          case 'data':
            dataSections.push({ objFile, section });
            break;
          case 'bss':
            bssSections.push({ objFile, section });
            break;
          case 'rodata':
            rodataSections.push({ objFile, section });
            break;
        }
      }
    }

    if (codeSections.length > 0) {
      this.emitComment('Code Section');
      this.emitLine('SECTION "Code", ROM');

      for (const { objFile, section } of codeSections) {
        for (const symbol of objFile.symbols) {
          if (symbol.section === section.name && symbol.type === 'function') {
            this.emitLine(`${symbol.name}:`);
          }
        }

        if (section.contents.length > 0) {
          this.emitBytes(section.contents);
          this.emitLine('');
        }
      }
    }

    if (dataSections.length > 0) {
      this.emitComment('Data Section');
      this.emitLine('SECTION "Data", WRAM');

      for (const { objFile, section } of dataSections) {
        for (const symbol of objFile.symbols) {
          if (symbol.section === section.name && symbol.type === 'variable') {
            this.emitLine(`${symbol.name}:`);
          }
        }

        if (section.contents.length > 0) {
          this.emitBytes(section.contents);
          this.emitLine('');
        }
      }
    }

    if (bssSections.length > 0) {
      this.emitComment('BSS Section (Uninitialized Data)');
      this.emitLine('SECTION "BSS", WRAM');

      for (const { objFile, section } of bssSections) {
        for (const symbol of objFile.symbols) {
          if (symbol.section === section.name) {
            this.emitLine(`${symbol.name}:`);
            this.emitLine(`  DS ${section.contents.length || 1}`);
          }
        }
      }
    }

    if (rodataSections.length > 0) {
      this.emitComment('Read-Only Data Section');
      this.emitLine('SECTION "ROData", ROM');

      for (const { section } of rodataSections) {
        if (section.contents.length > 0) {
          this.emitBytes(section.contents);
          this.emitLine('');
        }
      }
    }

    this.emitLine('');
    this.emitLine(`START:`);
    this.emitLine(`  jp ${entryPoint}`);
    this.emitLine('');
    this.emitLine('END START');

    return this.lines.join('\n') + '\n';
  }
}
